### ISSUE TITLE
Feature Request: Artillery Mark/Fire

### ISSUE THREAD

**Issue by TyroneMF** [zen-mod/ZEN#1]
A module which creates a target for Artillery to fire at. With a supporting module allowing artillery (or group of artillery) to fire at that target with spread pattern, rounds fired & how many artillery units will fire.

**Comment by mharis001** [comment]
Good idea. Would you prefer a module that you place to select a target or the 3D cursor selecting and click?

**Comment by TyroneMF** [comment]
Personally I prefer module placement as it allows multiple options for targets

**Comment by jonpas** [comment]
Support for ACE Mortars would be nice, when manual ammo handling is enabled. Add rounds automatically.

**Comment by mharis001** [comment]
#3 should have what you requested. I will look into support for ace mortars.

**Comment by Endstufe1203** [comment]
Hello,
i would like to have the opportunity to see the time of flight before the units are firing.

Maybe to give the units a time on target fire mission.
In short: i want to control when the impacts are on target!

**Comment by TheRadiumDude** [comment]
Closing this issue as the originally requested feature has been added.

If you wish to have additional features added to this specific part of ZEN, please open a new issue.
Thanks!
