### ISSUE TITLE
Feature Request: Rotate objects

### ISSUE THREAD

**Issue by CreepPork** [zen-mod/ZEN#104]
Useful module for rotating objects so you don't have to flip them with altitude and perhaps adding local flipping to visualize what it would look like would be incredibly useful but dunno how do-able it is.

**Comment by synixebrett** [comment]
I would rather this just be a keybind that rotates the  selected object, much easier to use than a module for quick rotations

**Comment by mharis001** [comment]
Don't think local visualization is possible to do and not sure how a keybind would work.
