### ISSUE TITLE
Zeus Interface gets stuck in infinite loop trying to open when respawnOnStart = 1

### ISSUE THREAD

**Issue by CreepPork** [zen-mod/ZEN#113]
This occurs in vanilla Zeus as well, and I'm doubtful it can be fixed but I'm creating an issue here to maybe start work on a fix, if possible.

The issue leaves the Curator in an infinite loop of the Curator interface trying to start but it then closes and the map (with the position/loadout options selected) appears but then quickly disappears. And this behaviour continues until the Curator is forced to exit the game via ALT-F4 or in some other way ending the process.

Perhaps a Feedback tracker ticket could be created as well.

**Comment by mharis001** [comment]
Possible fix may be to delay the curator interface forcing until the player has respawned (maybe checking `playerRespawnTime == -1`). Would require modification of `BIS_fnc_moduleCurator`.

**Comment by ColdEvul** [comment]
Is this tracked in the Arma 3 bug tracker anywere?

**Comment by CreepPork** [comment]
> Is this tracked in the Arma 3 bug tracker anywere?

No idea if it is.

**Comment by dedmen** [comment]
> Is this tracked in the Arma 3 bug tracker anywere?

If you add it, please link this ticket, and ping @killzonekid 
please provide repro mission file
