### ISSUE TITLE
Feature Request: Teleport Poles

### ISSUE THREAD

**Issue by SchwererKonigstiger** [zen-mod/ZEN#124]
Add teleport poles that players can use to teleport from one pole to any others, similar to [Achilles](https://github.com/ArmaAchilles/Achilles/blob/master/@AresModAchillesExpansion/addons/modules_f_ares/Player/functions/fn_PlayerCreateTeleporter.sqf).
These are fairly useful for letting players travel back and forth between positions.

**Comment by mharis001** [comment]
Will be added by #122 .

**Comment by bux** [comment]
Or use ace's [rallypoint feature](https://ace3mod.com/wiki/framework/respawn-framework.html) ;)
