### ISSUE TITLE
Feature Request: Disable Zeus Inventory Animation

### ISSUE THREAD

**Issue by bux** [zen-mod/ZEN#127]
An option to disable the Zeus Animation would be very welcome (if at allpossible).

**Comment by mharis001** [comment]
Already possible through the [`zen_common_disableGearAnim`](https://github.com/zen-mod/ZEN/blob/master/addons/common/initSettings.sqf#L11)setting.

**Comment by bux** [comment]
awesome!!! thanks a bunch :)
