### ISSUE TITLE
Bug: Dismissing placement of custom zeus modules with right click not working

### ISSUE THREAD

**Issue by diwako** [zen-mod/ZEN#13]
**Arma 3 Version:** `1.92` stable
**CBA Version:** `3.11.2` stable
**ZEN Version:** `1.0.0` stable

**Mods:**
```
- CBA_A3
- ACE3
- RHS full
- 3cb BAF
- 3cb factions
- group in house weapons, uniforms content mod
- ZEN
```

**Description:**
Dismissing placement of custom zeus modules with right click not working as intended.
Noticed while implementing custom modules that selecting a module and then using right click to dismiss the placement/execution of it only opens the context menu. Clicking right click again dismisses both context menu and module placement.

Expected behavior would be context menu not opening and module placement being canceled.

**Steps to reproduce:**
- create custom module
- preview ingame
- select custom module in modules tree
- right click on map to dismiss it

**Where did the issue occur?**
- Editor (Singleplayer)

**Additional information:**
Link to custom modules in question
https://github.com/diwako/fparma-mods/blob/zen_support/addons/ares/zenModules.sqf

**Comment by mharis001** [comment]
After some investigation, I can't reproduce the issue with just CBA and ZEN using the example custom module: `["Custom Modules", "Cool Hint", {hint str _this}] call zen_custom_modules_fnc_register`. The placement is dismissed when right click both on the map and off.

In the modules that you provided, does the issue occur with a specific one? or all of them?

**Comment by diwako** [comment]
Just retested it to be 100% sure. Happens on all modules. However the issue i described at first is a little different. The module always gets dismissed, as it should be.  The context menu opens most of the times, but not always. That one to reproduce is a bit weird, most times it opens, then sometimes it does not.

I personally would prefer it to not open when dismissing a module.

**Comment by mharis001** [comment]
Would you prefer it to not open when dismissing just a module or any placement type? Could definitely add a setting for those that would prefer this?

What about with opening with keybind? Should that cancel the placement and open or not open at all?

**Comment by diwako** [comment]
IMO i think the best ux case is when hitting the context menu keybind (which i kind of forgot existed) it should cancel the placement of any module and open the context menu.

A general setting as you suggested would probably fix that. it would either "dismiss and open context menu" or "dismiss and do not open context menu"  with either rightclick or key binding.
Dismissing a module is meant as dismissing any module or placement such as units.

**Comment by bux** [comment]
> I personally would prefer it to not open when dismissing a module.

same

> The context menu opens most of the times, but not always. That one to reproduce is a bit weird, most times it opens, then sometimes it does not.

That happens to me too

**Comment by mharis001** [comment]
Decided to not add a setting and just implement the best UX behaviour. Using the keybind will always open the menu by cancelling the placement. Using the mouse button, will not open the menu if placement is active (will cancel the placement).
