### ISSUE TITLE
Make ZEN optional on the client side

### ISSUE THREAD

**Issue by SekiAlpha** [zen-mod/ZEN#138]
**Is your feature request related to a problem?**
Yes, my issue is related to a problem. It's not a technical problem but more of what my the users in my unit prefer. In my unit, we used to use Achilles and we still do use it but I also added ZEN as an optional mod. The problem is that users who don't ZEUS or users who don't like ZEN when they try and load into the server without the mod they get a message telling them about version incompatibilities and then I get a bunch of users messaging me about it.
![image](https://user-images.githubusercontent.com/12445848/63723319-2152dd00-c823-11e9-96ce-c5db636f6dd3.png)
![image](https://user-images.githubusercontent.com/12445848/63723329-2879eb00-c823-11e9-82e7-9884ca9422a3.png)

**Solution you'd like:**
Make ZEN not spew out version mismatch messages if a client logs into the server without ZEN

**Alternatives you've considered:**
Removing ZEN from the optional list and making it required, or removing ZEN all together. Currently, the Zeuses in my unit prefer Achilles over ZEN so ZEN will probably be removed.

**Additional context:**
I would like this mod to be optional mainly because it would make it viable for my unit to do tests with it and provide more feedback.

**Comment by jonpas** [comment]
I am not very familiar with the project, but I strongly assume it isn't as easy as you put it, and probably wasn't in Achilles either. Functionalities depend on being able to be executed on clients where they have to be.

> users who don't ZEUS

They won't see a difference.

> users who don't like ZEN

It only adds things, so you don't have to use it or touch it's menu or modules.

**Comment by neilzar** [comment]
ZEN is not designed to be client-only and won't be at any point in the future either. Achilles still exists to be a client-only option for those that want a client-only option. We are working hard to bring the functionality that is currently in Achilles to ZEN, so depending on what people don't like about Achilles, they may never be happy.

As for running ZEN and Achilles together, don't. There are many overlapping functionalities, specifically related to the UI, that will cause issues.

**Comment by SekiAlpha** [comment]
Oh, I just looked back at this issue and I just want to clarify something. I would like ZEN to be optional on the client-side. It's fine if it has to be loaded on the server, but it would be nice for people who are not zeusing to not have to load the mod.

**Comment by mharis001** [comment]
ZEN is not designed to be an optional client-side mod, and it will not be changed to act as one in the future. Making a mod optional creates many hurdles and ultimately detracts from the code quality.
