### ISSUE TITLE
Feature Request: New options in the Fire Support section

### ISSUE THREAD

**Issue by GeneralKong** [zen-mod/ZEN#139]
**The Request**
More options in the Fire Support section in the Modules section

**Details:**
The Addition of SuperWeapons to the Fire Support section, more specifically, Nukes and EMP's, and maybe even a chemical weapon that creates a mist effect and causes damage to anyone that enters the area it is placed (with the area being able to be modified

**Comment by mharis001** [comment]
Don't think an EMP is going to be feasible to do.
