### ISSUE TITLE
Feature Request: Module & Faction Curator Restrictions

### ISSUE THREAD

**Issue by DaSnowFangs** [zen-mod/ZEN#142]
[Achilles](https://steamcommunity.com/sharedfiles/filedetails/?id=723217262) has a CBA setting which allows you to restrict the modules and factions that a curator has access to. This is really handy for streamlining the zues experience by only including relevant factions. This also prevents less experienced curators from placing wrong units. Same applies, in the modules that a curator would have access to.

It would be great to have in Zeus Enhanced and would allow my unit to finally move onto Enhanced fully.

![ReferenceImage](https://user-images.githubusercontent.com/51308025/63784577-23826d80-c8ef-11e9-81da-fc02c57b8486.JPG)

**Comment by DaSnowFangs** [comment]
Bump :)

**Comment by neilzar** [comment]
No need to bump, someone will get around to it at some point.
