### ISSUE TITLE
Feature Request: Pylon/Magazine Loadout Attribute

### ISSUE THREAD

**Issue by neilzar** [zen-mod/ZEN#143]
**Is your feature request related to a problem?**
There is no way to edit the loadout on pylons or normal magazines.

**Solution you'd like:**
Similar to Achilles, have a loadout button in the attribute screen which gives you a dialog to edit the loadout of a vehicle, both the pylons and magazines. Haven't really worked out a design.

**Alternatives you've considered:**
Achieve it using modules, but I think that is more of an inconvenience.

**Comment by CreepPork** [comment]
Could use the same design as the vanilla game in the Eden editor to display the aircraft and then the slot. ACE has a similar system but it's a module.

**Comment by neilzar** [comment]
That works for the pylons, but not sure how something like that could be designed for magazines in muzzles/turrets.

**Comment by CreepPork** [comment]
Enlighten me as I can't come up with a good use case for editing muzzles/turrets?

**Comment by neilzar** [comment]
In our community the tank crew like to get HE-FRAG loaded in their tanks, which isn't part of the standard loadout. We have a module that we use to edit the loadout so we can remove magazines and add others. We also use it if we want to limit the ammo available to crew, if we only want them to have 2 magazines of HEAT instead of 4, for example. Moving the slider halfway would change all ammo to half, so just editing the amount of HEAT magazines available is the only solution.

It is also for this reason I have created #140 because that means the ammo slider takes into consideration the changes made to the magazine loadout.

**Comment by CreepPork** [comment]
In the realm of Arma 3, I guess the most functional way would be to use a combo box? There shouldn't be too many choices of ammunition to load on a single magazine (non-aircraft) so I think that'd be the best choice.

**Comment by neilzar** [comment]
In our community we use the following combo box setup:
![image](https://user-images.githubusercontent.com/3193528/63789128-018ce900-c8f7-11e9-9ffb-069bb88872c4.png)
I think though that it would be better if the bottom two would be replaced by an inventory style system. There are weapons/muzzles that can have a whole lot of magazine types, although a lot of them are duplicates. I don't know why, but duplicates are very common...

**Comment by CreepPork** [comment]
That would be probably a better solution, but there should be a choice to offer the weapon to any crew member in the vehicle.

**Comment by neilzar** [comment]
I don't think you can change that with magazines, those are related to the turret, not the gunner. It would allow you to make the driver the gunner, seems weird to me.

**Comment by CreepPork** [comment]
Commander has weapons too and sometimes the driver also has their own magazines (e.g. smoke from RHS) and that could be potentially transferred to the commander/gunner. Yeah, moving the main cannon to the driver would be insanity but sounds like some good fun.

**Comment by neilzar** [comment]
I don't think that is really needed, those weapons are always located in the position of that slot. Turn-out for the commander gives access to an M2, for example.

**Comment by neilzar** [comment]
Looking at the BI wiki, it seems that you need to assign magazines to weapons, not turrets to fire them.

**Comment by oOKexOo** [comment]
The fancy approach would be an arsenal-like interface / expanding the garage, but probably a bit too ambitious.

**Comment by neilzar** [comment]
Something like that is probably too fancy and cumbersome. Something like the ACE Configure Pylons interface would be perfect, where the right-hand side could be used for the magazines. Although having the saved loadouts for vehicles would be a cool idea to have as well, so that would be another part in the interface which makes it a bit cluttered.

At least, this is the inspiration I am working with for now.
![image](https://user-images.githubusercontent.com/3193528/63816090-21dc9800-c937-11e9-8e41-916785ed538a.png)
