### ISSUE TITLE
Incompatibility: Diwako's STALKER-like anomalies (and possibly more)

### ISSUE THREAD

**Issue by zeue** [zen-mod/ZEN#150]
**Expectation:**
Loading Zeus Enhanced (ZE) and Diwako's STALKER-like anomalies (DSA) should allow access to both ZE functionality and DSA modules from within Zeus.

**Problem:**
When loading ZE and DSA, only ZE modules show within the modules area of Zeus. DSA modules are not visible.

**Note:**
I see that more popular modules are maintained with ZE enabled, such as the ACE modules and 3CB ones, however, DSA works on vanilla and Achilles-enabled Zeus interfaces, but not with ZE enabled.

I have no idea how ZE functions at the moment, but if there are required steps to "enable" or "whitelist" certain modules then I don't mind setting up a PR for it.

**Sources:**
- [Diwako's STALKER-like anomalies](https://steamcommunity.com/workshop/filedetails/?id=1383903166)

**Comment by mharis001** [comment]
This sounds like something that the STALKER mod would have to fix, and I don't see how ZEN would break any other mod's modules. ZEN uses its own separate module framework (not BI's). Tagging @diwako

**Comment by diwako** [comment]
Hey @zeue ,
My anomaly mod has NOT been updated in a while. So there is no zen support as of now. I will be updating the anomaly once ACE medical updates will be released.
I am fairly busy with real life stuff, but you can drop a feature request at the github project of that mod https://github.com/diwako/stalker_anomalies/

Alternatively wasn't there a feature on github to move the issue to some other repo or make a relation to it? @mharis001

**Comment by mharis001** [comment]
Transfer only works within the same organization and I don't know about relation. Closing since the incompatibility concerns have been addressed.
