### ISSUE TITLE
Improve Loadout Editing UX in a unit’s context menu

### ISSUE THREAD

**Issue by bux** [zen-mod/ZEN#151]
**Is your feature request related to a problem?**
As a game master I would like to quickly access the (ACE) Arsenal UI for a unit.

**Solution you'd like:**
Add an option to the context menu when right clicking a unit to open the (ACE) Arsenal for said unit. (e.g. as a child entry in "Edit Loadout")

**Alternatives you've considered:**
A configurable modifier key while clicking a unit could be a viable alternative.

**Comment by mharis001** [comment]
This should already be possible by clicking the "Edit Loadout" itself. It will open an arsenal on the unit based on the Preferred Arsenal setting.

Same with the "Edit Inventory" action. I guess it might be unclear that you can click the action itself since it has children actions.

**Comment by bux** [comment]
> I guess it might be unclear that you can click the action itself since it has children actions.

This

**Comment by bux** [comment]
I‘d rename the main action to „Loadout“ and have two child actions “Edit” and “Copy”.

**Comment by jonpas** [comment]
> I‘d rename the main action to „Loadout“ and have two child actions “Edit” and “Copy”.

This, but keep the main action available as clickable, as in shortcut for the first sub-action.
