### ISSUE TITLE
Zeus UI lockup

### ISSUE THREAD

**Issue by Camtheguy** [zen-mod/ZEN#152]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ZEN Version:** `1.x.x` (stable / dev + commit hash)

**Mods:**
```
- ZEN addon mods like composition
- CBA_A3
- ZEN
- TFAR
```

**Description:**
Using Zeus Enhanced during a op for a group and after using a module entire UI freezes up preventing continuation of the op. If we try to relog all we end up getting is the strum of the guitar trying to get back into zeus.

**Steps to reproduce:**
Unknown, so far we have linked it to ZEN and using modules.

**Where did the issue occur?**
- Dedicated Server

**Additional information:**
- We are using a virtual zeus system if that might be helpful

**Comment by mharis001** [comment]
Any specific module that causes this? The "strum of the guitar" when trying to get back into Zeus is a vanilla issue, requires respawning to fix..

**Comment by CreepPork** [comment]
Is this not associated with #113? Maybe it's not directly a module? What's your mission setup?

**Comment by Camtheguy** [comment]
we cant respawn since zeus is a entity rather than it being a player

**Comment by Camtheguy** [comment]
we use virtual zeus

**Comment by CreepPork** [comment]
The game will auto respawn the virtual entity if the flag is not set. Can you upload your mission files?

**Comment by Camtheguy** [comment]
It doesnt seem to do that at all, ill look into getting the mission files from the server owner

**Comment by Camtheguy** [comment]
[ZGM_Echelon_International.VR.pbo.zip](https://github.com/zen-mod/ZEN/files/3570617/ZGM_Echelon_International.VR.pbo.zip)

**Comment by Camtheguy** [comment]
here is the mission file guys

**Comment by Camtheguy** [comment]
Also if you could help us out in another way, do you guys recommend player zeus or virtual?

**Comment by synixebrett** [comment]
Encountered this the other day, not sure what lead up to it. I'll be recording my gameplay from now on to see if it happens again

**Comment by Fros7bite** [comment]
One of my Zeuses from the same community confirmed that after he stopped using Zeus Enhanced, the issue stopped for the last few days. 

This issue can be replicated by simply bringing up any module menu and closing it repeatedly.

There is a small chance your UI will lock up seemingly randomly, without any way to even hit escape to respawn or disconnect.

**Comment by mharis001** [comment]
I was unable to reproduce it by opening a module dialog repeatedly. The issue of being "unable to hit escape" sounds like a KeyDown EH returning true. However, no module display in ZEN does that.

**Comment by CreepPork** [comment]
Does it only occur on a dedi? Has anyone experienced it elsewhere?

**Comment by MGZoltan** [comment]
Can confirm. This happens almost consistently on a Dedicated server with a Zeus module (not linked to a player) primarily after using ZEN Arsenal to set up an enemy (via ACE Arsenal.) Thought it was Achilles+ZEN but after testing, opening ANY UI, tfar, attributes, etc, after doing so has a high chance to just totally lock up the game and require restarting. Dying, going back to menu, etc, nothing fixes it.

**Comment by VilsX** [comment]
Have managed to recreate this issue with crash to desktop on dedicated server. 

1. Add units using "ACE Utilities" option
2. Remove units using "Ace Utilities" option

https://pastebin.com/QHWAzQd8
https://pastebin.com/Cu7qT6rg
https://www.youtube.com/watch?v=pwXjtwx3Yxg&feature=youtu.be

Arma 3 Version: Latest
CBA Version: 3.11.2 (stable / dev + commit hash)
ZEN Version: 1.4.1 (stable / dev + commit hash)

**Comment by bux** [comment]
"Removing Units" crashing the game is a vanilla bug.

**Comment by VilsX** [comment]
It was also causing lock-up as well as the "Ambient Animation" module. 

Didn't realise removing units was a vanilla issue, would you like me to create a separate issue for that? 

I'll update CBA tonight and let you know if it's that.

**Comment by KappyTheLimey** [comment]
Not entirely sure that this issue is the same however we run ZEN on a dedicated server and something seems to lock up our Zeus Team individually at different times to the point where they have to Alt+F4 and rejoin only to not be able to go back into Zeus. Giving them access via the module freezes the server for 5-6 seconds which is not good considering we have about 100 members on any particular night.

We whitelist using SteamID for our Zeus so no matter which slot they jump into, they have the capability to access Zeus.

I have confirmed with them that they either use any module and it sometimes happens or just panning around in the camera view and it happens. RPT logs do not point to anything wrong with the mod including local and server based RPT.

**Comment by mharis001** [comment]
@KappyTheLimey Can you confirm whether this happens with just vanilla Zeus?

**Comment by KappyTheLimey** [comment]
The only function that freezes on vanilla Zeus is the add editable objects but I think that has been broken for years.

**Comment by mharis001** [comment]
Vanilla doesn't have an "editable objects" module for Zeus. To be more specific, can you confirm whether the input lockup (required ALT-F4) occurs with vanilla Zeus (no mods leaded).

**Comment by KappyTheLimey** [comment]
Apologies, it appeared some of my mods were still enabled, I booted up Vanilla ArmA and no crashes.

**Comment by bux** [comment]
> "Removing Units" crashing the game is a vanilla bug

@VilsX It's a vanilla bug. Updating CBA doesn't help.

**Comment by TheOtherGuy3** [comment]
> It was also causing lock-up as well as the "Ambient Animation" module.

it not  just Ambient Animation as it seems to be any module in Zeus. me and my guys have encounter it using "toggle flash light", editing an AI's loadout , opening an AI's edit menu and "suicide bomber" modules to name a few. 

https://www.youtube.com/watch?v=ORXZZyZSGPk 
in the video as soon as i open the "toggle flash light" module my game locks up 

https://www.youtube.com/watch?v=Y-CeGfkN9s8&feature=youtu.be

**Comment by Fros7bite** [comment]
To note, this also happens occasionally with Achilles, yet much less often.

**Comment by MGZoltan** [comment]
This issue is still extant, and happens on attributes. It mostly seems to happen at semi-random but can be encouraged by setting loadouts via the ACE Arsenal at the least. Pretty much the only reason I don't use ZEN at the moment.

**Comment by bux** [comment]
We're using Zen very often and quite extensively and never had this happen before. Please check your mod lists. There might be something interfering.

**Comment by MGZoltan** [comment]
There isn't. I've tried ZEN on it's own, and I still get this issue. It's almost always after setting loadouts and opening attributes, but isn't completely consistent.

 Thank you for the anecdote, glad it Works On Your Machine.

**Comment by dedmen** [comment]
Zeus in my unit experienced this for the first time last weekend. But.. We don't run zen yet. so...

**Comment by MGZoltan** [comment]
Do you have any idea what _might_ cause something like this? Even a shot in the dark would help.
Do you think it's at all possible that it's related to it being a dedicated server, potentially under load?

**Comment by CollisionBF** [comment]
Anyone have any ideas? My group is also having the same issues on the Zeus UI just completely locking up. When the Zeus UI locks up they also have to alt + f4 because they cant do anything once this happens. Sometimes it even happens at the start where the Zeus UI wont even start up and the zeus is stuck on the ground with no UI. This didn't seem to start happening until we switched over to ZE, and now that Achilles has updated its doing it on that as well.

**Comment by KappyTheLimey** [comment]
> This didn't seem to start happening until we switched over to ZE, and now that Achilles has updated its doing it on that as well.

Then the issue isn't Zen. It could range from Vanilla to one of the dependant mods such as CBA/ACE.

Our issues seemed to have resolved itself.

**Comment by TheOtherGuy3** [comment]
> > This didn't seem to start happening until we switched over to ZE, and now that Achilles has updated its doing it on that as well.
> 
> Then the issue isn't Zen. It could range from Vanilla to one of the dependant mods such as CBA/ACE.
> 
> Our issues seemed to have resolved itself.

Last time I was on server it was still doing it. We found a fix for it though.... If someone kills you when you're frozen in the camera it will take you back to the respawn screen and then you can carry on as normal

**Comment by BlackSeaSurfer** [comment]
I had this bug on my dedicated Server.

I had only been in for about 10 minutes, placed about 30 units.

Used about ~5 ACE Patrol Modules, ~3 ACE AI Garrison Modules.

On the last Garrison Module the interfaced locked up as if I were using a dialog box. I was unable to use my mouse but I was able to use some keyboard functions (like toggling the compass and entity list typing in chat), but was unable to press escape. I was able to login to admin and restart the mission.

I tried reproducing this but was unable to in the same time that it had happened.

I have another member in my group who has this issue more often then I do, but I also have members who that have never had it.

My modlist that my group and I use: 
https://steamcommunity.com/sharedfiles/filedetails/?id=1311120055

The work around that our group has been doing is have the Zeus be kicked by the current Admin and rejoin. But this isn't a fix we are willing to settle with.z

If it's disposable maybe a key that'd close all current dialog box's would do the trick, again not sure if that's possible.

**Comment by mharis001** [comment]
That seems to imply that this issue may be caused by ACE Zeus modules. Just to confirm, when the issue occurred, you only used the ACE modules that you listed and nothing else?

**Comment by BlackSeaSurfer** [comment]
Correct I only had the ACE AI category opened.

Patrol & Garrison

Didn't get the chance to do any thing else.

**Comment by NyteMyre** [comment]
I have had this issue 2 times in tonights op and this github page showed up when i google searched it. Our group is using ZEN as well

**Comment by NyteMyre** [comment]
Here are two clips of it happening to me:

https://clips.twitch.tv/DreamyPowerfulWatermelonTheRinger
https://www.twitch.tv/nytemyre/clip/BrainyEndearingFalconPJSugar?

**Comment by tyl3r99** [comment]
It happened to me very recently

long story short, my game master module bugged out and did not give me Zeus (not sure why as I had the variable name in the owner box) anyway... I joined and found that Zeus was not working so.. 

using ace I logged in as admin on the server and "create Zeus" through ace interaction. 
from that moment all my UI got locked up pretty much. 

Hope this info is ok.

**Comment by vuneswe** [comment]
Have had this happen to me on a local server with friends, very annoying. Happened when I clicked tried to edit a vehicle, seems to happen when opening a UI with Zeus. Next time it happens I will try to shadowplay it.

**Comment by TheRadiumDude** [comment]
Can confirm that the issue seems to occur quite consistently when you open and close dialogs repeatedly. Is it possible that the control lock-up that occurs when you open a dialog is not releasing properly, and may be exacerbated by a slower server/client execution?

**Comment by tyl3r99** [comment]
Mine only locks up when making zeus through ace interaction menu otherwise
its okay

**Comment by BlackSeaSurfer** [comment]
I continue to get this without using ACE modules, when opening units attribute menus, and using the Ambient Animations module to list two. I've been able to to close the invisible dialog box but sitting for a while spamming Escape, Tab, Enter and the arrow keys There really isn't any rhyme or reason I guess I just eventually hit close on the dialog box...

**Comment by Wardak1680** [comment]
I just mash my keyboard. It usually works.

**Comment by neilzar** [comment]
After a lot of testing found the following reproduction steps that worked for me:

Mods: ZEN, CBA, ACE
Steps:
- Spawn a unit/group and edit one of the units in the ACE arsenal.
- Delete the unit/group.
- Spawn a new unit/group and open attributes again. UI will lock up after the attributes opened.

Additional observations:
- Basically, all keybinds that don't interact with the attribute display still work as if it is closed. You can use the arrow keys to move around the attributes display and escape to close it, but normal function doesn't return.
- Hitting escape closes the visible display, but in the background it will function as if it is open. So using arrow keys you can move around the display, and you can use enter to interact as if left clicking. I was able to enter the code execution box that way and close the Zeus display from there. I was not able to see what I was typing because the display was visually closed.
- Only happened with ACE arsenal, not BI. Modules also continued to work normally. My guess is that this is only part of the problem, but #542 should be a catch-all hack fix.

**Comment by neilzar** [comment]
After further testing I found that spawning a new unit is not required. Using any module that creates a dialog will cause the UI to lockup.

So current repro steps are:
- Load any mission
- Spawn unit
- Open arsenal on unit, and close again. Nothing needs to be done in the arsenal.
- Delete unit
- Use any modules that opens a dialog or spawn a new unit and open its attributes.

**Comment by mharis001** [comment]
Also, reproducible with only CBA and ACE. Use the Arsenal module and open any dialog after deleting the unit.

**Comment by NyteMyre** [comment]
> Also, reproducible with only CBA and ACE. Use the Arsenal module and open any dialog after deleting the unit.

Does it also happen if you delete the corpse of the unit? I've encountered the lock-up quite a few times and i do change AI units gear with arsenal now and then, but i usually don't delete them when they are alive.

**Comment by neilzar** [comment]
> > Also, reproducible with only CBA and ACE. Use the Arsenal module and open any dialog after deleting the unit.
> 
> Does it also happen if you delete the corpse of the unit? I've encountered the lock-up quite a few times and i do change AI units gear with arsenal now and then, but i usually don't delete them when they are alive.

Yes. I found that killing a unit and then deleting it will also lockup the UI. I guess it also happens when the unit is deleted through scripts, because it apparently happens quite often in my community and we have a cleanup script to take care of dead bodies.

**Comment by neilzar** [comment]
Fix has been merged https://github.com/acemod/ACE3/pull/8102
