### ISSUE TITLE
Ambient FlyBy Enter Command

### ISSUE THREAD

**Issue by GeneralKong** [zen-mod/ZEN#165]
**The Request:**
Place-able arrows for ambient flyby module

**Details:**
The Ability to place down the Ambient Flyby in a way to allow you to place multiple arrows (like you get when you are placing down the USS Freedom and USS Liberty), and when you press enter, it will spawn them all at the same time in the direction the are pointing, making it easier to have them fly in formation

**Comment by callofmarty** [comment]
Hi, not sure if i can post it here. Is it possible to make the flyby module remember last entered settings?

**Comment by mharis001** [comment]
This seems very cumbersome to try to implement and I am not sure if its the best UX as well. The Ambient Flyby module recently received some improvements such as selection saving and an amount of aircraft option.

I think the combination of those two should make what you want to accomplish much easier (and remove the need to add any sort of ENTER confirmation to the module).

**Comment by GeneralKong** [comment]
Agreed, with the new changes there really is no need anymore for this change
