### ISSUE TITLE
With hidden zeus interface, the lines from the visiblity check are visible

### ISSUE THREAD

**Issue by AdlerSalbei** [zen-mod/ZEN#171]
**Arma 3 Version:**  (stable)
**CBA Version:**  (stable)
**ZEN Version:**  (stable)

**Description:**
- While hidding the Zeus Interface, the lines from the visibility check are visible.

**Steps to reproduce:**
- Open Zeus
- Move Mous into Players View
- Press Backspace to hide HUD

**Where did the issue occur?**
- Dedicated 

**Screenshots:**
https://imgur.com/a/RHgbDhk

**Comment by mharis001** [comment]
Should be fixed in the latest release (v1.4.1 - PR #135). Can you double check your mod version.

**Comment by AdlerSalbei** [comment]
Ah nice, did not see the PR. Version is 1.4.0.
Thanks.
