### ISSUE TITLE
Global AI skill module

### ISSUE THREAD

**Issue by callofmarty** [zen-mod/ZEN#177]
Same module as in Achilles addon.
Change with slider General skill, weapon handling, spotting distance etc....

**Comment by callofmarty** [comment]
ah, this option is in ace modules. My bad.
My apologies.

**Comment by mharis001** [comment]
No worries. I think I better understand your request now. A module that globally sets the skill(s) of all AI and any AI created afterwards - something I think the ACE equivalent does not do - could be useful.
