### ISSUE TITLE
Context menu option: Update Editable Objects

### ISSUE THREAD

**Issue by SceptreOfficial** [zen-mod/ZEN#178]
**Is your feature request related to a problem?**
When trying to manage objects in zeus, updating editable objects can become a slight chore to find and place the module every time.

**Solution you'd like:**
It would be nice to have a default context menu action for the "Update Editable Objects" function to accompany the "Teleport Zeus" action.

**Comment by MGZoltan** [comment]
Would love this as well, real QoL feature.

**Comment by mharis001** [comment]
What would you suggest for range sub-actions, i was thinking: 5m, 25m, 100m, and 250m. And should this add/remove for all curators or just the local one?

**Comment by SceptreOfficial** [comment]
Oh yeah sub actions are a great idea to speed it up even more. My initial thought was to just have it open the same dialog as the module.
Those ranges seem good to me. I dont play with multiple curators, so I dont know what would be best for locality. Maybe worth a cba setting?

**Comment by mharis001** [comment]
Opening the dialog could work too, it's just the module displays aren't really setup to work without a logic.

When I read the issue, my thoughts were to have actions like this:

- Update Editable Objects
    - Add
        - 5m
        - 25m
        - 100m
        - 250m
    - Remove
        - 5m
        - 25m
        - 100m
        - 250m

Either requires sending an event to the server, it's more about what is the better behaviour. I think a setting for this is unnecessary.

**Comment by SceptreOfficial** [comment]
Gotcha, in that case I think that setup would work fine.
IMO it should just be local. For me, the point of this is to speed up organizing the on-screen clutter. If people want more options, the module can provide that.
