### ISSUE TITLE
UX discrepancy with context menu

### ISSUE THREAD

**Issue by bux** [zen-mod/ZEN#20]
**Arma 3 Version:** `1.92`
**CBA Version:** `3.11.2`
**ZEN Version:** `1.1.0`

**Mods:**
```
Zeus Enhanced 1.1.0
[SOB] BW EinsUstg v3.4.0
[SOB] SOBMod v5.0.0
Community Base Addons v3.11.2
Bundeswehr Mod Compatibility PBO v2.1-1
Bundeswehr Mod
Advanced Combat Radio Environment 2
Advanced Combat Environment Extras 3.4.2
Advanced Combat Environment 3.12.6
```

**Description:**
- Context menu of an unselected and a selected unit is different

**Steps to reproduce:**
- Open Zeus
- Select Unit
- Right click on said unit
- Deselect Unit
- Right click on said unit
- Observer how the context menu misses entries

**Where did the issue occur?**
- Dedicated

**Additional information:**
![image](https://user-images.githubusercontent.com/1235520/60356264-d8bca600-99d0-11e9-99a0-fa5d4d95d0cb.png)

![image](https://user-images.githubusercontent.com/1235520/60356276-deb28700-99d0-11e9-83a3-3b8056d6b52f.png)

**Comment by mharis001** [comment]
I think this is because when you select one unit in Zeus it also selects the group. But, when you open the context menu on a hovered (not selected) unit it only adds the unit, not its group. Can fix by adding the group of a hovered unit to the selected arrays.
