### ISSUE TITLE
Allow searching the EDIT column

### ISSUE THREAD

**Issue by Bluscream** [zen-mod/ZEN#202]
**Is your feature request related to a problem?**
The CREATE column has a nice searchbar that helps finding stuff quickly but i'm missing that functionality on crowded maps for the EDIT column to search for a unit by name for example

**Solution you'd like:**
Duplicate the search bar to the EDIT column

**Alternatives you've considered:**
Uninstalling the game

**Additional context:**
[REDACTED]

**Comment by mharis001** [comment]
Don't think this is actually possible. The entities tree is (like most with Zeus) hard-coded and constantly refreshed making it not possible to search. In addition, the state of the tree affects which editable object icons are visible - something I think searching would create problems with.

**Comment by Bluscream** [comment]
Oh, thats sad, thanks for the infos
