### ISSUE TITLE
Injury

### ISSUE THREAD

**Issue by KappyTheLimey** [zen-mod/ZEN#206]
I would like to have the ability to have a module to injure players and AI using a module to pick what type of injury and where on the person to create dynamic scenarios rather than resulting to disruptive methods such as shooting etc. 

The current issue is if you lower the health value on a selected unit, the injury does not show on the medical menu for players thus they are unable to treat the casualty short of a PAK.

Ares-Achilles have this module but we prefer the ZEN since updates are more regular and documented better.

**Comment by mharis001** [comment]
Closing in favour of more recent #452.
