### ISSUE TITLE
Interface Symbol

### ISSUE THREAD

**Issue by badwolf1358** [zen-mod/ZEN#207]
When using in conjunction with multiple other zeus interface mods it can be difficult to differentiate what module comes from which mod.

Would it be possible for a symbol representing the mod to be added next to modules from this mod. Similar to how Achilles does their spartan helmet?

**Comment by mharis001** [comment]
This is something that is possible but, in my opinion, not worth doing. I don't see it being important to know which mod adds which modules, especially at the cost increased display loading times.

**Comment by CreepPork** [comment]
I personally like this feature, but it's a matter of preference. A simple CBA setting would suffice and wouldn't increase loading times unless you opted-in to it.
