### ISSUE TITLE
Bug: Attach flag dropdown list not clickable

### ISSUE THREAD

**Issue by bux** [zen-mod/ZEN#21]
**Arma 3 Version:** `1.92`
**CBA Version:** `3.11.2`
**ZEN Version:** `1.1.0`

**Mods:**
```
Zeus Enhanced 1.1.0
[SOB] BW EinsUstg v3.4.0
[SOB] SOBMod v5.0.0
Community Base Addons v3.11.2
Bundeswehr Mod Compatibility PBO v2.1-1
Bundeswehr Mod
Advanced Combat Radio Environment 2
Advanced Combat Environment Extras 3.4.2
Advanced Combat Environment 3.12.6
```

**Description:**
- The options in the "Attach Flag" dialog are not clickable. The only working navigation for me is using the arrow keys on the keyboard

**Steps to reproduce:**
- Open Zeus
- Activate the Attach Flag module
- Click on a unit with it
- Try to select a flag by clicking on it

**Where did the issue occur?**
- Dedicated

**Additional information:**

![b19afcca3375eb7d5d61d5b494ea77da](https://user-images.githubusercontent.com/1235520/60356765-22f25700-99d2-11e9-9d64-2006ecf01c42.gif)

**Comment by mharis001** [comment]
Yeah, Arma combo box weirdness. Probably best to switch to a listbox control, should fix this.

**Comment by bux** [comment]
There are no other combo boxes that need to be replaced?

**Comment by mharis001** [comment]
I am not sure, the rest seem to be working fine for me at least. This one might have had an issue due to the large number of entries.
