### ISSUE TITLE
Create/ Edit Intel

### ISSUE THREAD

**Issue by TheOtherGuy3** [zen-mod/ZEN#213]
**Is your feature request related to a problem?**
its not causing an issue as such however, its a feature that lost when we switched from Achilles that was really useful as an indirect way of passing on information. 

**Solution you'd like:**
I would like a module that dose what the Create/ Edit Intel module did in Achilles. so we can EG put it on some documents, or a body for players to search. 

**Alternatives you've considered:**
I haven't thought of any Alternatives for what this module offers. 

**Additional context:**
N/A

**Comment by CreepPork** [comment]
Closed, duplicate of #29.
