### ISSUE TITLE
Feature Request: Copy Mission SQF

### ISSUE THREAD

**Issue by neilzar** [zen-mod/ZEN#220]
**Is your feature request related to a problem?**
People in my community like to make a mission beforehand, copy the mission into an SQF using Achilles' `Copy to Mission SQF`, and then run the SQF at the start of the session so all objects and markers are pre-placed.

**Solution you'd like:**
A module to copy the mission objects, markers, etc. to an SQF that can be run using the `Execute Code` module

**Comment by bux** [comment]
Wait, they use Zeus beforehand and want to copy that into a Zeus mission?
If so, why don’t they place everything in the editor?

**Comment by neilzar** [comment]
It is infeasible in our community to have everyone create missions in the editor. We run multiple Zeus missions every day, so that would be a lot of custom missions to check for quality; especially because we have missions of 50+ players every day and at least 3 people wanting to Zeus each day. We decided to make simple templates with only have a few Arsenal crates in a remote spawn area, that way most of the map is usable for the Zeuses. There usually is enough time to set up a mission while the platoon is in the briefing, but some people like to go into more detail and therefore set up stuff beforehand.

We also have had very little success with the editor SQF copy function, we found the Achilles one to be far more reliable.

**Comment by EpsilonCommunity** [comment]
@neilzar You could use a Debug Console. To execute a script.

**Comment by EpsilonCommunity** [comment]
May I ask why this was closed?

**Comment by CreepPork** [comment]
> May I ask why this was closed?

The feature has been implemented and is present in our testing candidates. Once we deem it to be stable enough, we'll release the update.

**Comment by EpsilonCommunity** [comment]
Thanks for the update
