### ISSUE TITLE
Create IED doesn't destroy/remove object it has been used on. Object can't be used again.

### ISSUE THREAD

**Issue by bux** [zen-mod/ZEN#23]
Zen 1.1.0

![image](https://user-images.githubusercontent.com/1235520/60357143-233f2200-99d3-11e9-8142-8cb302f008b2.png)

One can't use the same object after the explosion with the "Create IED" module again.

**Comment by mharis001** [comment]
I guess some objects do not get destroyed by the explosion. Probably best to manually `setDamage` on it and destroy it.
