### ISSUE TITLE
Spawn Reinforcements: Slow down aircraft when approaching an LZ

### ISSUE THREAD

**Issue by bux** [zen-mod/ZEN#262]
**Is your feature request related to a problem?**
Not sure if this is a real bug report. I had some troubles when using the paradrop function with an MH-6. When approaching the LZ the velocity of the MH-6 was too high and it always overshot the LZ having to do circles again and again. When manually setting it to limited speed it was able to successfully paradrop the reinforcements. The same is happening when letting a heli fastrope its units or land. Or when a plane (blackfish infantry transport) is trying to paradrop units.

**Solution you'd like:**
Add a waypoint with the "limited" speed setting a few 100 meters before the actual LZ.

**Alternatives you've considered:**
Having an aircraft always fly at limited speed. But story telling wise that might not always be preferred.

**Comment by CreepPork** [comment]
Making AI fly all the time in Limited, would be catastrophically slow.

**Comment by oOKexOo** [comment]
I'm pretty sure it has to do with the updating of the move waypoint. It's something that the Achilles paradrop doesn't do. This ensures that they eject the first time, however, in the few cases the chopper goes for an unexpected route, they might eject a bit off from the LZ. From my experience it's worth to pay that price.
