### ISSUE TITLE
Set forecast for weather module

### ISSUE THREAD

**Issue by zharf** [zen-mod/ZEN#277]
**Is your feature request related to a problem?**
Current weather module changes weather instantly

**Solution you'd like:**
Would like to be able to set forecasted values. I realise that Arma's weather system is weird and doesn't change some values very quickly (eg. clouds), but would still like to be able to change the forecast. Still better than an abrupt change.

A slider for the current weather module to pass as the time parameter for the many weather calls would work for me even though they're not exactly reliable, passing 0 could still be instant like it is now (with `forceWeatherChange` call)

**Additional context:**
See issue #30

**Comment by mharis001** [comment]
When originally creating the module, there was an option to select the amount of time over which the weather change would occur. However, I observed inconsistent behaviour over which time the change took effect in multiplayer, and as result, removed that option.

If I recall correctly, smooth transitions might be possible, just not within a precise time frame. Maybe just two options for the transition - "Instant" or "Smooth" - would be better. I will do some testing.

**Comment by mharis001** [comment]
After doing some testing, I think the only possible thing would be just an instant or smooth option, and even that isn't very consistent. Without `forceWeatherChange` the weather change on the client "lags behind". For example, when changing from minimal overcast to full overcast - the client takes significantly longer to reach the desired value. And when high overcast values are reached on the client, the cloud cover doesn't reflect that.
