### ISSUE TITLE
Achilles UI Compatibility

### ISSUE THREAD

**Issue by PandaSt0rm** [zen-mod/ZEN#28]
**Mods:**
```
- CBA_A3
- ZEN v1.1.0
- Achilles v1.2.2
```

**Description:**
[Achilles](https://github.com/ArmaAchilles/Achilles), which is another Zeus enhancement based on the outdated Ares, has a slight  compatibility issue with ZEN in terms of the UI Modification ZEN does on Zeus, where the Achilles footer in the 'Create' menu becomes a bit wonky. See the attached image.
![](https://i.imgur.com/reO1g8M.png)

**Comment by oOKexOo** [comment]
Closed in favour of ArmaAchilles/Achilles#510
