### ISSUE TITLE
Deep copy units spawn for the wrong curator

### ISSUE THREAD

**Issue by SayaKiozumi** [zen-mod/ZEN#295]
In a hosted game, deep copied units (Ctrl+Shift+C) spawn at the host's cursor position when pasted by any other curators (Ctrl+Shift+V) instead of their own.

Steps to reproduce:
1. Host a game.
2. Host and another player has curator.
3. Have the other player deep copy and paste a unit.
4. The unit is spawned at the hosts's cursor location.

**Comment by mharis001** [comment]
Results from spawning on server but not getting position from client. Will be fixed by #144 .
