### ISSUE TITLE
Create/Edit Intel Module fails to create a diary entry

### ISSUE THREAD

**Issue by aptncy** [zen-mod/ZEN#297]
**Arma 3 Version:** `1.96` (stable)
**CBA Version:** `3.13.0` (stable)
**ZEN Version:** `1.6.1` (stable)

**Mods:**
```
- CBA_A3
- ZEN
- ACE
```

**Description:**
- The Create/Edit Intel Module does not create a diary entry upon collecting intel. I have so far tried creating intel via the module, adding intel to an existing object, and adding intel to an AI. In all of these cases there is no intel added to the diary. The issue occurs when I place intel for other players and vice versa.

**Steps to reproduce:**
- Place Module
- Enter information into the intel title and description
- Collect Intel
- Check Diary

**Where did the issue occur?**
- Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer)

**Additional information:**
- This issue occurs regardless of mods loaded.

**RPT log file:**
- https://pastebin.com/6XRwNUrD

**Comment by synixebrett** [comment]
I have the same issue

**Comment by mharis001** [comment]
Test is local-hosted MP, working as expected. Is there any specific situation in which the intel does not get added as a diary entry?

**Comment by synixebrett** [comment]
I am using dedicated MP, we have never had the diary entry appear

**Comment by aptncy** [comment]
> we have never had the diary entry appear

Same here. I've tested the module in every scenario short of a dedicated server, no diary entries added. This has been the case throughout multiple modpacks and everybody that I Zeus for has reported no new diary entries.

**Comment by mharis001** [comment]
Was able to reproduce, issue occurs when action uses ACE Interaction Menu - works as expected using BI's hold actions.
