### ISSUE TITLE
Feature Request: Advanced Weather Change

### ISSUE THREAD

**Issue by luke-metcalf** [zen-mod/ZEN#30]
Instead of the Vanilla Zeus module in which you can just apply rain, overcast suddenly. There should be a module to allow for a smoother transition over to new weather. Such as increase in rain, overcast increases over a period of time. 
![Advanced Weather Change](https://user-images.githubusercontent.com/23123952/60385067-242c8e00-9a7d-11e9-8c88-b1a72d37eafd.jpg)

**Comment by oOKexOo** [comment]
Side note: Should think how to make it compatible with ACE's weather system.

**Comment by ckjpdx** [comment]
+1
I don't care about all the settings Achilles had, but a gradual change over 5 minutes would be excellent instead changing instantly.

**Comment by mharis001** [comment]
Cloud cover seems to update very slowly in order to reflect the set overcast value. And using `forceWeatherChange` causes an instant update. Because of this, I don't think it is possible to have any "fast" gradual changes in weather (for example: 5 minutes, sunny to cloudy)
