### ISSUE TITLE
Mk41 VLS not compatible with Artillery Fire Mission Module

### ISSUE THREAD

**Issue by nobodyshome** [zen-mod/ZEN#300]
**Arma 3 Version:** `1.96.146114` (stable)
**CBA Version:** `3.14.0.200207` (stable)
**ZEN Version:** `1.6.1` (stable)

**Mods:**
```
@efx_dust;
@efx_lighting;
@rhsusaf;
@rksl_attachments;
@rksl_public;
@spyder_addons;
@suppress;
@tfar;
@virtus;
@3cb_baf_equipment;
@3cb_baf_units;
@3cb_baf_vehicles;
@3cb_baf_weapons;
@ace;
@ace_compat_rhs_usf3;
@ace_compat_rksl_pm_ii;
@acex;
@advanced_sling_loading;
@advanced_towing;
@advanced_urban_rappelling;
@backpack_on_chest;
@boeing_ch-47f;
@boxloader;
@camofaces;
@cba_a3;
@ctab;
@enhanced_movement;
@grad_trenches;
@immersion_cigs;
@kat_notebook;
@3den_enhanced;
@ArmaZeusCache;
@zeus_enhanced;
```

**Description:**
- Artillery Fire Mission doesn't consider the "Mk41 VLS" an Artillery Unit

**Steps to reproduce:**
- Place "NATO > Turrets > Mk41 VLS" 
- Attached "Artillery Fire Mission" to VLS

**Where did the issue occur?**
- Dedicated

**Comment by mharis001** [comment]
Will be resolved by #40 .
