### ISSUE TITLE
Display player  name only 

### ISSUE THREAD

**Issue by TheOtherGuy3** [zen-mod/ZEN#301]
**Is your feature request related to a problem?**
The unit display name covers up the player name on the edit menu. 
https://gyazo.com/52516a3afbce2681282cddd4db39b38f

**Solution you'd like:**
An Option to have only player names visible.

**Alternatives you've considered:**
Changing unit names on the mission file but a setting that could do this would be nice :)

**Comment by mharis001** [comment]
Don't think this is possible to do due to the hard-coded nature of the Zeus entities tree and from what I can tell there is no way to get what unit a tree entry refers to.
