### ISSUE TITLE
Reinforcements Fastrope too high-RHS

### ISSUE THREAD

**Issue by LtBabyface** [zen-mod/ZEN#302]
**Arma 3 Version:** stable
**CBA Version:** `3.14.0` stable
**ZEN Version:** stable

**Mods:**
```
- CBA_A3
- ZEN
- ACE3
- RHSSAF
- RHSGREF
- RHSUSAF
- RHSAFRF
- ACE/RHS compat files
```

**Description:**
- When deploying reinforcements by fastrope non-vanilla helicopters hover several meters too high. Infantry are injured falling the remaining distance. Vanilla helicopters manage just fine.

**Where did the issue occur?**
- Dedicated

**Additional information:**
- This could very well be a problem with RHS/ACE.

**Comment by mharis001** [comment]
I was unable to reproduce the issue of units being injured but did notice that helicopters may hover higher than the set `flyInHeight`. I think decreasing that will also fix your issue.
