### ISSUE TITLE
Copy-Paste issue

### ISSUE THREAD

**Issue by neilzar** [zen-mod/ZEN#309]
**Arma 3 Version:** `1.96`
**CBA Version:** `3.14.0` (stable / dev + commit hash)
**ZEN Version:** `dev 547aea5` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ZEN
```

**Description:**
- When copy-pasting a large number of objects/vehicles it can paste twice. I copied 10 vehicles, then when pasting those it seemed to sometimes spawn two sets in the same spot, causing them to blow up. I had the placement preview enabled but I am unsure if that causes the issue. More likely caused by not correctly detecting a single press.

**Steps to reproduce:**
- Copy a large number of vehicles.
- Paste.
- ???
- Carnage.

**Where did the issue occur?**
- Self-Hosted Multiplayer

**Additional information:**
- Unsure what number causes the issue, but there is a noticeable lag spike when pasting. Possible that it somehow pastes twice in that time. Secondary testing confirmed that holding CTRL+V for almost a second caused it while a quicker tap of it did not all the time.

**RPT log file:**
- I checked the log, nothing in there.

**Comment by mharis001** [comment]
This is just base game Zeus behaviour? Holding down CTRL + V will repeatedly pastes objects.

You can't paste while placement is active so placement review should not have any issues with this.

**Comment by mharis001** [comment]
Closing as I don't think we can do anything about this. Copy-pasting in Zeus is handled by the engine.
