### ISSUE TITLE
Switch allied status on unit kill

### ISSUE THREAD

**Issue by Glenn-Lambert** [zen-mod/ZEN#310]
**Is your feature request related to a problem?**
In scenarios where the player group (bluefor) conducts a surprise coup/raid/attack against another side (bluefor/redfor), the zeus sometimes uses the function to switch alliances status of fractions  from friendly to hostile in a specific suitable moment. This method prevents early enraging ai-forces and increases the chance for a successful simulation of surprising attacks. For example: Bluefor prepares an attack on greenfor (sneaking in position) - greenfor is allied with bluefor in that moment - bluefor starts shooting on greenfor - after a few seconds greenfor gathers and starts counterattack (because zeus changes allied status).

In scenarios with multiple player groups or a lot of simultaneously happening events, this can be very tricky to coordinate. If the switch will not be coordinated on point, the scenario will be boring and feel like clay pigeon shooting.

**Solution you'd like:**
A module that can be casted on a unit our group (greenfor in our example), if this unit dies by fire of another fraction, the alliance status changes automatically and immediate (or with short delay) to hostile.

**Alternatives you've considered:**
A module that has a radius and affects different units or groups in that radius. Or maybe affects the whole fraction.

**Comment by mharis001** [comment]
Closing as I don't think this will be worked on and is likely too specific for inclusion in ZEN.
