### ISSUE TITLE
Feature Request: Add Switch Unit module that supports group commands (remote control)

### ISSUE THREAD

**Issue by Pinecone227** [zen-mod/ZEN#313]
Im not sure if this is a feature request or a bug but I'd assume the latter since it was featured in Achilles.

**Comment by neilzar** [comment]
Could you be a bit more specific?

**Comment by Pinecone227** [comment]
If you remote control a squad leader as Zeus, you cannot give out orders to his AI subordinates. It shows as if he wasn't in a squad at all and the units just follow

**Comment by CreepPork** [comment]
It's more a feature request than a bug because how the remote control works limits groups on the BI side of things.

You're looking for the Switch Unit module which is not implemented yet.

**Comment by oOKexOo** [comment]
This is a duplicate. Closed in favor of  #54.
