### ISSUE TITLE
Stop deep copy/paste & custom compositions from altering face.

### ISSUE THREAD

**Issue by GordonWeedman** [zen-mod/ZEN#321]
**Is your feature request related to a problem?**
Deep copying a unit or making a composition of a unit or a group of units also copies the face, so you end up with an army of clones if you use it a lot.

**Solution you'd like:**
Stop deep copies/pastes and custom compositions from also setting the face. Maybe a toggle in the cba settings so people can choose for themselves. 
Maybe also do this for facewear? Some units have random facewear.

**Comment by mharis001** [comment]
For custom compositions, could have a toolbar-like toggle button in the panel to choose if randomization is enable..
