### ISSUE TITLE
Add a Light Source Module, so you can tie an object to the existence of light in an area

### ISSUE THREAD

**Issue by CPTMiller** [zen-mod/ZEN#326]
For missions where you have to blow up an generator to make a blackout in an area. Dont know if this has been suggested before, but it would be nice to be able to do so on the fly.

**Comment by mharis001** [comment]
A light source module already exists. If you mean, add functionality to the module to allow it to be linked to an object - I think that is likely too specific and easily achievable using a killed EH by the curator.

**Comment by CPTMiller** [comment]
Sorry for bad explanation. What I meant was a way to make power-grid go down in a specific area, tied to an object. 

I know there are scripts to do so, but it would be way more awesome if you could do it realtime while in zeus. Just a thought :)

**Comment by mharis001** [comment]
You can use the "Toggle Lamps" module to set the state of lights in a given area.
