### ISSUE TITLE
zen_context_menu_fnc_removeAction for existing actions

### ISSUE THREAD

**Issue by nomisum** [zen-mod/ZEN#333]
For reasons I need to remove the default actions for a restricted Zeus.

This works well for a bunch of actions but some are not found. What am I doing wrong or is this just not supported yet?

```
{
    [_x] call zen_context_menu_fnc_removeAction;
} forEach 
[
    "Heal", // doesnt work
    "Stance",
    "Loadout",
    "Editable Objects", // doesnt work
    "Remote Control", 
    "Inventory",
    "Vehicle Appearance", // doesnt work
    "Teleport Zeus", // doesnt work
    "Remote Control",
    "Captives"
];

```

**Comment by mharis001** [comment]
`removeAction` needs the action names in the action path (not the displayed name). For example, "Heal" should be "HealUnits" [reference](https://github.com/zen-mod/ZEN/blob/master/addons/context_actions/CfgContext.hpp#L181).

**Comment by nomisum** [comment]
thanks a lot! appreciate your work 👍

**Comment by nomisum** [comment]
not possible for `Create Area Marker` though it seems 🤔

**Comment by mharis001** [comment]
For that it would be `zen_area_markers` [reference](https://ace3mod.com/wiki/development/setting-up-the-development-environment.html).
