### ISSUE TITLE
Light Source module doesn't have an icon when placed down

### ISSUE THREAD

**Issue by CreepPork** [zen-mod/ZEN#334]
**Arma 3 Version:** `1.96` (stable)
**CBA Version:** `3.x.x` (stable)
**ZEN Version:** `1.7.0` (stable)

**Mods:**
```
- CBA_A3
- ZEN
```

**Description:**
- When placing down the Light Source module there is no icon on the module itself

**Steps to reproduce:**
- See the module in the create tree have an icon
- Place down the module
- See the default icon

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Additional information:**
N/A

**RPT log file:**
N/A

**Screenshots:**
https://gyazo.com/0ccc45bf7cc2149edf1a4c8196f40603

**Comment by mharis001** [comment]
The module doesn't have an icon (other than the default gear), so this is not really a bug.

**Comment by CreepPork** [comment]
Perhaps, but still think it should have at least something. Don't the Eden modules have the same gear icon placed down? If they do, then I would classify this as a bug.
