### ISSUE TITLE
Quick action to teleport the Zeus

### ISSUE THREAD

**Issue by CreepPork** [zen-mod/ZEN#336]
**Is your feature request related to a problem?**
When you are a unit, that has hidden from view and you run TFAR, you might sometimes want to move your unit around more quickly (SR is too noisy, want to hear local chatter). I would use the teleporter module, but it is cumbersome to find your unit in the list.

**Solution you'd like:**
One of these should suffice:
- Context menu action to teleport the Zeus
- Teleport module has a button near the OK to teleport the Zeus only

**Alternatives you've considered:**
Might have to consider multiple Zeuses too but I wouldn't think we should at all.

**Additional context:**
Might have missed this in ZEN already.

**Comment by mharis001** [comment]
A Teleport Zeus context menu action already exists.
