### ISSUE TITLE
Patrol module places its waypoints under the floor

### ISSUE THREAD

**Issue by CreepPork** [zen-mod/ZEN#338]
**Arma 3 Version:** `1.96` (stable )
**CBA Version:** `3.x.x` (stable)
**ZEN Version:** `1.7.0` (stable)

**Mods:**
```
- CBA_A3
- ZEN
- CUP Terrains - Core
- CUP Terrains - Maps
```

**Description:**
- Placing a patrol module on top of a unit will cause waypoints to be created under the ground. This makes them editing harder and possibly may or may not affect AI's ability to route to the points.

**Steps to reproduce:**
- Place down a unit (in Takistan (tested it here only))
- Put the patrol module on top of it
- See that the waypoints are under the ground

**Where did the issue occur?**
- Dedicated (only tested it here)

**Additional information:**
- ACE does it too, should be fixed there too.

**RPT log file:**
N/A

**Screenshots:**
N/A

**Comment by mharis001** [comment]
The module calls `CBA_fnc_taskPatrol` to create the waypoints, might be an issue with CBA.

**Comment by mharis001** [comment]
Will be fixed in CBA by CBATeam/CBA_A3#1322.
