### ISSUE TITLE
How to add nested context menu actions through script

### ISSUE THREAD

**Issue by alezm00** [zen-mod/ZEN#345]
Hi i want to create an action list in the Context Menu with [Scripts](https://zen-mod.github.io/ZEN/#/frameworks/context_menu?id=adding-actions-through-script)

but i can't manage to create a sub action inside another.
Can someone paste me an example! :)

i want to create soleting like:
MAINACTION
└─ subaction

thx :)

**Comment by mharis001** [comment]
The key is action names and the resulting action paths. For example, first add a main action and then the sub-actions to the main action (you can go as deep in terms of the nesting as you want).

```sqf
private _mainAction = ["MainAction", "Main Action", "", {hint "main"}] call zen_context_menu_fnc_createAction;
[_mainAction, [], 0] call zen_context_menu_fnc_addAction;

private _subAction = ["SubAction", "Sub Action", "", {hint "sub"}] call zen_context_menu_fnc_createAction;
[_subAction, ["MainAction"], 0] call zen_context_menu_fnc_addAction;

private _anotherAction = ["AnotherAction", "Another Action", "", {hint "another"}] call zen_context_menu_fnc_createAction;
[_anotherAction , ["MainAction", "SubAction"], 0] call zen_context_menu_fnc_addAction;
```

**Comment by alezm00** [comment]
thanks for the help
