### ISSUE TITLE
Custom compositions feature at the bottom left of the Create menu causing the menu to be softlocked

### ISSUE THREAD

**Issue by Vynity** [zen-mod/ZEN#347]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ZEN Version:** `1.x.x` (stable / dev + commit hash)
^ All latest versions, confirmed by up-to-date arma 3 launcher message.

**Mods:**
```
- CBA_A3
- ZEN
https://steamcommunity.com/sharedfiles/filedetails/?id=2035664501
```

**Description:**
- Whenever I tried to expand the tree nodes or scroll down using the Create menu, it won't let me. However, when I switch to units, modules, or markers, it lets me, but i still can't use the tree nodes for things like respawn, objectives, nato, csat, etc.
Sometimes, when I make a map, and set everything up accordingly, the compositions don't show up at the bottom and everything works perfectly normally.

**Additional Note:**
Whenever I load up a Master map, it infinitely loads. I can hear birds and other things like that as well.

**Steps to reproduce:**
- Just launching up Arma 3 and playing any Zeus scenario.

**Where did the issue occur?**
- Multiplayer.

**Additional information:**
- Sometimes, the first time i load in Zeus, I think the custom composition doesn't show up. I might be wrong, though.
- I know this isn't any other mod because i picked out mods one by one, even unloaded zeus enhanced and loaded every other mod.
- The composition itself may be having issues because when i play Zeus Enhanced with no other mods, it doesn't show up.

**RPT log file:**
https://pastebin.com/H8Vd2Xvv

**Screenshots:**
http://prntscr.com/rrvqns

http://prntscr.com/rrvrh0

**Comment by mharis001** [comment]
What do you mean by dropdowns? Expand tree nodes?

What do you mean by compositions don't show up at the bottom? Is the custom compositions panel not showing up?

If possible, can you provide video show casing the issue with only CBA and ZEN loaded. Also, an upload the RPT.

**Comment by Vynity** [comment]
> What do you mean by dropdowns? Expand tree nodes?
> 
> What do you mean by compositions don't show up at the bottom? Is the custom compositions panel not showing up?
> 
> If possible, can you provide video show casing the issue with only CBA and ZEN loaded. Also, an upload the RPT.

Yes, I meant the tree nodes.

The so-called compositions at the bottom i was talking about has been put in screenshots, two variations.
I also added an RPT as you requested. I will fulfill your other requests as soon as possible.

**Comment by Vynity** [comment]
> > What do you mean by dropdowns? Expand tree nodes?
> > What do you mean by compositions don't show up at the bottom? Is the custom compositions panel not showing up?
> > If possible, can you provide video show casing the issue with only CBA and ZEN loaded. Also, an upload the RPT.
> 
> Yes, I meant the tree nodes.
> 
> The so-called compositions at the bottom i was talking about has been put in screenshots, two variations.
> I also added an RPT as you requested. I will fulfill your other requests as soon as possible.

About one of your other requests, I ran it with CBA and Zeus Enhanced only, and the compositions could not re-appear. However, every other mod I have does not mention anything about custom compositions. So I still think it's a ZEN-only problem.

I have a couple of theories of why this is happening:
1:
It has something to do with resolution.
2:
Setting the "all workshop addons can be used" on the zeus module may have something to do with it.

**Comment by mharis001** [comment]
Okay, that is definitely an issue. Just to confirm, the compositions panel that you highlighted in the screenshots works as expected with just CBA and ZEN? That is, it is only visible when the selected mode is groups and the selected side is empty.

**Comment by Vynity** [comment]
> Okay, that is definitely an issue. Just to confirm, the compositions panel that you highlighted in the screenshots works as expected with just CBA and ZEN? That is, it is only visible when the selected mode is groups and the selected side is empty.

Just playtested, and yes, it works perfectly fine. The composition works fine when I used it when it is glitched as well.

**Comment by mharis001** [comment]
If the issue does not occur with just CBA and ZEN then it has to be caused by another mod or the specific mission that you are playing. Can you try a blank mission with your modset and see if the issue persists. Other than that I am not sure what else can be done on this end unless a specific cause can be identified.

**Comment by Vynity** [comment]
Okay, so I found out the troublemaker.
It seems Achilles was also getting issues from this.
It seems Zeus Enhanced has incompatibility with the Auto-Medic mod.
I disabled it, and, well, Zeus Enhanced worked again!
Issue fixed, I guess.

**Comment by mharis001** [comment]
Okay, glad you solved the issue.

**Comment by Vynity** [comment]
Thanks for helping!
