### ISSUE TITLE
Single Player game, save and exit, modules disapper upon loading save file.

### ISSUE THREAD

**Issue by redalpha123123** [zen-mod/ZEN#358]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ZEN Version:** `1.x.x` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ZEN
```

**Description:**
When you save a Single Player game and save and exit then load the save the modules are no longer there. 

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Additional information:**
- Provide any additional information that will help us solve this issue.

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

**Screenshots:**

**Comment by CreepPork** [comment]
If I recall correctly, this is a BI bug and it did affect Achilles the same way.

**Comment by mharis001** [comment]
I think this has been resolved by adding the `PreloadAddons` config. If the issue persists, please re-open.
