### ISSUE TITLE
Cannot use the right click context menu to edit loadouts of units preplaced into Zeus missions in the 3D editor when playing the mission on a dedicated server

### ISSUE THREAD

**Issue by Qerbas** [zen-mod/ZEN#360]
**Arma 3 Version:** `1.96.146114` (stable)
**CBA Version:** `3.15` (stable)
**ZEN Version:** `1.7.1` (stable)

**Mods:**
```
- CBA_A3
- ZEN
```

**Description:**
- Cannot use the right click context menu to edit loadouts of units preplaced into Zeus missions in the 3D editor when playing the mission on a dedicated server

**Steps to reproduce:**
1. Load my test mission on a dedicated server
2. Try to edit the loadout of the unit using the right click context menu and notice that the arsenal does not open.
3. Try placing a unit with the Zeus interface and notice how you can still edit the unit's loadout 

**Where did the issue occur?**
- Dedicated

**Additional information:**
Test mission: [Zen_Test.Altis.zip](https://github.com/zen-mod/ZEN/files/4453083/Zen_Test.Altis.zip)

**RPT log file:**
[Server RPT](https://gist.github.com/Qerbas/14746a01c6a6dfab6f887a41be34cedf) 
[Client RPT](https://gist.github.com/Qerbas/9ec2974f7dc3f1a2063f7e5b94b6017b)

**Screenshots:**
https://i.imgur.com/zvVO62c.jpg

**Comment by neilzar** [comment]
What do you mean with "you cannot", what doesn't happen with the editor placed unit that does happen with the Zeus placed unit? Does the option not show up or does the option not do anything?

**Comment by Qerbas** [comment]
Sorry made an edit when typing, what I meant is the Arsenal does not open.  Nothing happens.

**Comment by mharis001** [comment]
Does the menu close without the arsenal opening? Can you edit the loadout of editor placed units using the "Arsenal" module?

**Comment by Qerbas** [comment]
The menu closes without the arsenal opening.  I cannot edit the loadout of an editor placed unit using the "Arsenal" module.

**Comment by CreepPork** [comment]
This issue does exist. It happened once when we were running an operation. I think that the vanilla Arsenal module worked.

**Comment by mharis001** [comment]
Can't reproduce using the provided test mission. I think if there was an issue it would be with the arsenal itself instead of the context menu action. In terms of the Arsenal module, we replace the vanilla one with our own that calls the same common function to open the arsenal as the context menu action.

Please reopen if the issue persists and can be reproduced.
