### ISSUE TITLE
Reinforcements not Spawning

### ISSUE THREAD

**Issue by Lufian12345** [zen-mod/ZEN#370]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ZEN Version:** `1.x.x` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ZEN
- DUI - Squad Radar
- SST: Opposition
- Zombies and Demons
- CUP Terrains - Core
- CUP Terrains - Maps
- Vcom AI V3.3.3

```

**Description:**
- Reinforcements module not working
**Steps to reproduce:**
- Place RP module then place LZ module, go to spawn reinforcements, no reinforcements spawn

**Where did the issue occur?**
- Dedicated server

**Additional information:**
- Provide any additional information that will help us solve this issue.

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

**Screenshots:**

**Comment by bux** [comment]
Have you tried it with just CBA and Zen?

**Comment by mharis001** [comment]
As @bux said, please confirm that the issue occurs with just CBA and ZEN. Also, please fill out the version information.

**Comment by mharis001** [comment]
Closing as no response and unable to reproduce with the given information.
