### ISSUE TITLE
Double clicking a unit opens 2 menus 

### ISSUE THREAD

**Issue by Pi2tpur** [zen-mod/ZEN#372]
**Arma 3 Version:** `x.xx` stable
**CBA Version:** `3.x.x` stable 
**ZEN Version:** `1.x.x` stable
**Mods:**
```
- CBA_A3
- ZEN
-armazuescache
```

**Description:**
- Add a detailed description of the error. This makes it easier for us to fix the issue.

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.
when given curator or even logging into the server as admin to access zues, you double click a unit or object and the window that appears, instead of one 2 show up. so when you hit ok on one, the other one is there with default information, they seem to work either one you use, but it anoying to have to close 2 and sometimes i can mess up what objective or setting you have put into it
**Where did the issue occur?**
- Dedicated

**Additional information:**
- Provide any additional information that will help us solve this issue.

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

**Screenshots:**

**Comment by mharis001** [comment]
What do you mean by "given curator"? Is the curator module created during the mission (not placed in 3DEN)?

**Comment by Pi2tpur** [comment]
promote to zues, so if you go to the zues tab of modules, you have promote to zues. my unit says give curator that could be an old term, my bad

**Comment by mharis001** [comment]
No worries, just wanted to make sure I understood correctly. Does the issue still occur on dedicated if someone uses a module placed in 3DEN (not using the Promote to Zeus module)?

**Comment by Pi2tpur** [comment]
yes. it happens to both, more so to giving someone zues, but it does happen when you log into zues since we use #adminlogged gamemaster module

**Comment by synixebrett** [comment]
I reported this over two years ago
https://feedback.bistudio.com/T127588

**Comment by mharis001** [comment]
The issue occurs because BI's module framework is bugged for `isGlobal > 0` modules created after mission start, in that the function is executed twice on clients. This was the reason ZEN modules were moved away from BI's module framework onto one specifically for Zeus.

With that said, I wouldn't expect the issue to occur for game master modules placed in 3DEN.
