### ISSUE TITLE
TFAR and remote control compatibility

### ISSUE THREAD

**Issue by Afgan0r** [zen-mod/ZEN#390]
**Is your feature request related to a problem?**
It's hard to speak with players because I need to make me invincible and teleport to the unit. Also, sometimes you can't become invisible because you not only Zeus but a player

**Solution you'd like:**
It's would be perfect if I can use shortcut Ctrl+left-click

**Alternatives you've considered:**
A separate module for remote control is also great

**Additional context:**
N/A

**Comment by mharis001** [comment]
I don't understand, isn't this a TFAR issue?

**Comment by Afgan0r** [comment]
I don't know
This feature was in Achilles in a separate module, but not on the default shortcut so I think that they made this module themselves

**Comment by synixebrett** [comment]
ACRE added support for Zeus, it seems like it should be on TFAR to implement this on their side

**Comment by oOKexOo** [comment]
This is basically another request for implementing a module/key-bind for `selectPlayer`. Hence, it is a duplicate. Closed in favour of #54.
