### ISSUE TITLE
Use object serialization/deserialization API in export mission SQF?

### ISSUE THREAD

**Issue by oOKexOo** [zen-mod/ZEN#394]
I have the feeling that we are doing a lot of duplicate work by not using the object serialization/deserialization API for export mission SQF as well.

**Comment by mharis001** [comment]
The reason is the goal that Export Mission SQF should output code that can be executed independently of ZEN to restore the mission. Otherwise, we could just output serialized data calling the desalinize function.

**Comment by oOKexOo** [comment]
Well, I meant putting the definition of `zen_common_fnc_deserializeInventory` and `zen_common_fnc_deserializeObject` also in the output.
