### ISSUE TITLE
Feature Request: Reinforcements

### ISSUE THREAD

**Issue by MGZoltan** [zen-mod/ZEN#4]
In the vein of Achilles, a module that sees use fairly frequently by me is the Reinforcement module, allowing the selection of 

- The team providing the vehicle

- The vehicle in question (And number of non-crew slots)

- If the vehicle will remain at the drop point, or return from where it was summoned and despawn

- Insertion Method (if from Helicopter/Plane, ie landing or paradropping or rappelling (via ACE or Adv. rappelling)

- 'Fill' team (BLU/IND/OP)

- Unit fill. In Achilles, this is a maximum of 1 squad, chosen from Compositions of the team chosen.

- Deployed unit behaviour (Safe/Aware/Combat)

This specifically required 3 modules in Achilles- LZ (Allowing multiple, and given individual names- This is where the vehicle lands/stops/etc, deploying units), RP (where said deployed units were told to move), and the actual Spawn Units module, which created the vehicle at the module location and gave it the tasking to perform said troop dropoff.

Personally I would like to see the option of non-composition selection, or more than 1 squad (as squad sizes are not always equivalent to transportation capability). This could also be the framework for a 'supply drop' module, another feature Achilles had, allowing AI drop of vehicles/containers, etc.

**Comment by synixebrett** [comment]
Just my 2 cents, I don't think the RP is needed. It'll save time to skip it and just tell units where to go after landing

**Comment by oOKexOo** [comment]
Or better just make the need for a RP optional.

**Comment by NZF-JDWang** [comment]
RP's are really useful if you as a zeus want to add some random chance.

Eg often before a mission kicks off I'll place LZ's and RP's around the AO and then just select random, so the units land at a random LZ and move to a random rally point.

It's also super useful if you have more than one reinforcement group coming in at once. You don't have to micro as much.

**Comment by CreepPork** [comment]
But RPs still should be optional because sometimes you don't plan to call reinforcements so you haven't placed the RPs. Then you are in a rush to place them even though the situation doesn't require it.

**Comment by neilzar** [comment]
It has always bugged me how only your RP/LZ show up in the lists, but the ones placed by other Zeuses show up as blank entries.

**Comment by CreepPork** [comment]
> It has always bugged me how only your RP/LZ show up in the lists, but the ones placed by other Zeuses show up as blank entries.

That would also happen when the current Zeus left/crashed and rejoined.
