### ISSUE TITLE
Manual Fire/Aim module

### ISSUE THREAD

**Issue by Vynity** [zen-mod/ZEN#403]
**Is your feature request related to a problem?**
Yes. The AI in tanks, apcs, cars or helicopters will not fire at things, but merely aim at it. This is annoying when you want to make the AI tank fire at a helicopter.

**Solution you'd like:**
A manual fire module that lets you choose how many times it shoots after placement, if there's a delay, if you want them to reload after, or if you want them to aim at a target/area after placement. (Could be via line like Teleport Players, could also be a context menu option containing the line as well)

**Alternatives you've considered:**
I could just remote control, but this solution lets less time be wasted as well.

**Additional context:**
Can help helicopters/tanks aim better. AI Helicopters are annoying to use since they act like jets when they destroy something.
![tankboomexample](https://user-images.githubusercontent.com/63028399/84299619-a5f2bb80-ab16-11ea-913b-9abfce037886.jpg)

**Comment by ampersand38** [comment]
What do you think about this basic level of control?
https://www.youtube.com/watch?v=ml0xGoXfGY4
https://github.com/zen-mod/ZEN/pull/496
