### ISSUE TITLE
Ambient War/Quick War Module

### ISSUE THREAD

**Issue by Vynity** [zen-mod/ZEN#404]
**Is your feature request related to a problem?**
No, just a suggestion.

**Solution you'd like:**
A module that can spawn factions of the Zeus's choosing. If the setting is toggled, both factions (can be nato, aaf, csat, civilians, or modded) will know where eachother's spawned units are, and will fight eachother using what was given. Options could be: Tanks (specify faction, or both, specify number), APCs (same as last), (MRAPs) (same as last), (Armed MRAPs) same as last), Cars (same as last), Is [faction] retreating? (yes/no, possibly specify amount of troops/vehicles retreating) Is the warzone CQB? (yes/no) Warzone radius? (specify meters amount) Amount already dead (specify faction, or both, specify number) 

**Alternatives you've considered:**
Just making it, but it could save time for an ambush or some quick firefight that would take too long to setup and the player would already be there.

**Additional context:**
Example: The player sets down a moduloe in a flat field. The module gives these options, in order:
Faction 1: NATO, CSAT, AAF (etc, could include modded)
Faction 2: NATO, CSAT, AAF (etc, could include modded)
Faction 1 and 2's Infantry Count
Faction 1 and 2's Armor/Tanks
Radius of the placement field
Current casualties (corpses as decorations to immerse, randomly placed around the radius)
![quickwarmodule](https://user-images.githubusercontent.com/63028399/84300607-1bab5700-ab18-11ea-8a41-97709b51dc9c.jpg)

**Comment by CreepPork** [comment]
This is highly dependent on the mission and making a module that would suit every mission would be practically impossible. Also limits creativity and I'd believe that is truly out of scope for this addon.

I'll be closing this issue as out-of-scope.
