### ISSUE TITLE
Ignore Friendly Fire module

### ISSUE THREAD

**Issue by Vynity** [zen-mod/ZEN#407]
**Is your feature request related to a problem?**
Yes. Sometimes, when the players are doing stealth missions, they will wear disguises, so I set them as friendly using either Side Relations, or Group Side so they don't get attacked. This is also useful for when I set the enemy for Friendly until a conversation with them is over or something.

**Solution you'd like:**
A module that allows Zeus to enable Friendly Fire or not without the AI retaliating after a couple friendly fire kills. Zeus could set what side could retaliate, even if retaliation was off. It could also be used for things like PvP on the same side, or removing the (friendly fire) bit at the end of the PvP kill message.

**Alternatives you've considered:**
Changing sides before a fight begins. But that will be hard to do in time.

**Additional context:**
I think I've said enough context already.

**Comment by GCrane93** [comment]
an alternative is to add an option to edit the player rating.
eg `player addRating 2000;`
once a player's rating goes below -2000 they are swapped to enemy

**Comment by mharis001** [comment]
As commented above, you can probably use the `addRating` command or the `HandleRating` to prevent units from becoming part of `sideEnemy`. In terms of "side-specific retaliation", I am unsure of a clean way to accomplishing that. All in all, closing as I think this is too specific for ZEN and likely will not be worked on.
