### ISSUE TITLE
Create/Edit Squad/Regiment Marker

### ISSUE THREAD

**Issue by Vynity** [zen-mod/ZEN#410]
**Is your feature request related to a problem?**
Technically not, but it would help with creating an enemy indicator faster. Plus, it would be neat.

**Solution you'd like:**
A module/context menu module that allows you to place down a marker that lets you set what icon (like armored, infantry, stuff like that) with the dots at the top (which usually indicate if it's a squad, platoon, etc.). If possible, it could also have the ability to, when you hover over it, to display what the name of it is, and the icon of the stuff (like with ifrit regiments, etc.)

**Alternatives you've considered:**
Making it, but it would take a bit to place down perfectly, especially with the dots.

**Additional context:**
The campaign provides information about platoons and regiments. Basically what i'm talking about.

**Comment by mharis001** [comment]
As others have pointed out, this seems out of scope for a Zeus based mod. Closing as I don't think this will be worked on.
