### ISSUE TITLE
Remote control optimization

### ISSUE THREAD

**Issue by tiapfy** [zen-mod/ZEN#411]
When using the remote control command with a relatively large number of mods loaded (Ex: RHS + Project OPFOR), there is always a little freeze when acquiring or releasing control of a unit. I suppose this happens because the Zeus Interface reloads the list of entities from the config every time it is loaded. This often results in perceived lag for the player who sees the controlled AI he just killed freeze for a few seconds before falling on the ground.
If there was something you could do to optimize the interface, I think it would make the remote control command much less frustrating to use.

**Comment by mharis001** [comment]
There is nothing that can be done about this. That part of Zeus is all handled in engine so any fix would have to come from BI.

**Comment by tiapfy** [comment]
Thank you for the quick response
