### ISSUE TITLE
Feature request: Zeus visibility indicator viewdistance and group placement

### ISSUE THREAD

**Issue by shukari** [zen-mod/ZEN#421]
It would be nice if the visibility indicator can also check for the viewdistance of the players (or the ace viewdistance value `ace_viewdistance_limitViewDistance` if it is server/mission forced)
- `(["ace_viewdistance_limitViewDistance"] call CBA_settings_fnc_priority) in ["server", "mission"] && {_pos distance _eyePos < ace_viewdistance_limitViewDistance}`

Also nice would be if the place preview of groups is also considered for the visibility check. So if i place a group with the preview placement activ it should check if all units are visible.

https://github.com/zen-mod/ZEN/blob/86e4abd278815a7794725c30941447e876ed4b57/addons/visibility/functions/fnc_draw.sqf#L31-L45

**Comment by mharis001** [comment]
I think getting player view distances would require constantly broadcasting the `viewDistance` value; which I think we should avoid. Also, using the forced `ace_viewdistance` value might not always work as there could be other view distance management mods installed overwriting the value.

One option would be to add a "Check Distance" setting that controls the distance at which players are considered. But I am unsure about this as well.

Lastly, the Zeus placement UI is all in-engine and there isn't a straightforward way to get the positions of objects in the placement preview.

**Comment by Quailsnap** [comment]
>Lastly, the Zeus placement UI is all in-engine and there isn't a straightforward way to get the positions of objects in the placement preview.

Does this mean it's infeasible to have the Zeus visibility indicator only show when the Zeus is placing object(s)?
