### ISSUE TITLE
Copy Inventory

### ISSUE THREAD

**Issue by BenFromTTG1249** [zen-mod/ZEN#422]
Something that was in Achilles that I think would benefit this mod was the "Copy Inventory" and "Paste Inventory" options, as they allowed us to easily replicate specific inventories of objects. This could also be circumvented by having the inventory of an object remain the same when copy / pasting, even if it has been edited.

.

**Comment by CreepPork** [comment]
As this issue is two different things, it'd be nice if you could close this and create two separate issues? It helps us to track it too.

**Comment by mharis001** [comment]
There are context menu actions to copy/paste object inventories. Adding modules for these actions as well seems like bloat to me.

You can also deep copy/paste to preserve the object's inventory.

**Comment by BenFromTTG1249** [comment]
Ah right was not aware of that. Thanks very much
