### ISSUE TITLE
Loiter Waypoint

### ISSUE THREAD

**Issue by BenFromTTG1249** [zen-mod/ZEN#425]
A feature that I would like to see is the ability to set an AI Plane to "Loiter" around a way point, similar to the UAV option. This would make UAVs not controlled by the player and Armed Blackfish's way more useful

**Comment by mharis001** [comment]
How would this work best in terms of UX? We could add the `LOITER` waypoint type to the types toolbox but, loiter waypoints have additional options that can be set - loiter direction and radius. In 3DEN, if you change a waypoint to the loiter type, confirm, and then reopen the waypoint's attributes at the bottom there are these additional options.

We could mimic that:
- open waypoint attributes, select loiter type, and click OK
- reopen waypoint attributes
- set loiter options

A bit cumbersome to have to reopen the dialog but I think that is the simplest solution.

**Comment by BenFromTTG1249** [comment]
That sounds like the best way to me.
