### ISSUE TITLE
Deep Copy/Paste not functioning

### ISSUE THREAD

**Issue by Tazerfingers** [zen-mod/ZEN#428]
I want to use custom loadouts for my units and I want to use Deep Copy/Paste to do it. I use the correct keybinds and have even changed it to a different keybind, yet every time I attempt to copy/paste it results in Arma 3 playing the "Action Failed" sound, like trying to spawn units without enough resources. Is there a server setting I need to edit/fix needed in order for it to work?

**Comment by mharis001** [comment]
Duplicate of #429 .
