### ISSUE TITLE
Feature Request: Breachable Doors

### ISSUE THREAD

**Issue by guyanz** [zen-mod/ZEN#43]
A setting to set doors to "breachable" would be awesome! It's included in the vanilla game.

**Comment by CreepPork** [comment]
Is it in the vanilla game? I can't remember it being in vanilla Zeus.

**Comment by Gweezer** [comment]
+1 vote for this feature please, esp. if it's possible to shotgun breach.

**Comment by mharis001** [comment]
AFAIK this isn't a part of the base game. And the ability to breach locked doors via shotguns or explosives seems out scope for this mod.

**Comment by mharis001** [comment]
Closing for above reason.
