### ISSUE TITLE
Ambient flyby question 

### ISSUE THREAD

**Issue by tyl3r99** [zen-mod/ZEN#432]
can you choose whether the air vehicle that does a flyby i.e helicopter to have its light(s) on or force them off? 

Would be good to make a helicopter fly over with a search light

**Comment by mharis001** [comment]
You can open the spawned aircraft's attributes and turn its lights on.

**Comment by tyl3r99** [comment]
Oh okay thank you. It might be a bit of a pain but your right technically lol want me to close issue?

**Comment by mharis001** [comment]
No problem.
