### ISSUE TITLE
ZEN does not work in the editor when pressing "Preview" [SP]

### ISSUE THREAD

**Issue by tyl3r99** [zen-mod/ZEN#433]
**Arma 3 Version:**  (stable)
**CBA Version:** `cba_3.15.1.200418` (stable)
**ZEN Version:** `zen_1.8.0.20` (stable)

**Mods:**
```
- CBA_A3
- ZEN
- No other mods
```

**Description:**
- Zeus enhanced does work in the editor SP (preview) environment. 

**Steps to reproduce:**
- Go into editor (Altis)
place player unit down 
place game master module 
assign a variable name to player i.e. z1
put z1 in owner box in zeus module 
click preview 
go into zeus 
its vanilla stable 

**Where did the issue occur?**
- Editor (Singleplayer)

**Additional information:**
- Provide any additional information that will help us solve this issue.

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
[Arma3_x64_2020-07-10_18-47-14.zip](https://github.com/zen-mod/ZEN/files/4904671/Arma3_x64_2020-07-10_18-47-14.zip)

**Screenshots:**
![20200710184852_1](https://user-images.githubusercontent.com/7946533/87184703-615a6b80-c2e0-11ea-8940-9f6c343de595.jpg)
Above is editor SP
Below is Editor MP 
![20200710184916_1](https://user-images.githubusercontent.com/7946533/87184729-6d462d80-c2e0-11ea-8e5f-fe5e6c70f107.jpg)

**Comment by tyl3r99** [comment]
ah crap my 1st screenshot is the wrong tab sorry!!

but you get the idea of what bug im trying to report yeah? if need be i can start pc again and get correct screenshot.

**Comment by mharis001** [comment]
You mean ZEN modules don't show up. Currently, you have to select "All addons (including unofficial ones)" in the Game Master module. After #419 is merged, the default option "All official addons" will also work.

**Comment by tyl3r99** [comment]
Yeah only the default modules show up (vanilla game) even with the game
master module set to allow all unofficial mods.

**Comment by mharis001** [comment]
Can you provide an RPT and sample mission?

**Comment by tyl3r99** [comment]
Sure will do it today

**Comment by CreepPork** [comment]
Your .rpt indicates that you haven't loaded ZEN.

**Comment by tyl3r99** [comment]
I can confirm that it works now lol
I swear I had it loaded. "If" it happens again I'll make sure to record it
and send it to you alongside mission.pbo
