### ISSUE TITLE
Mod Is Not Signed by a Key Accepted by Server

### ISSUE THREAD

**Issue by theofficialRath** [zen-mod/ZEN#441]
**Arma 3 Version:** `Launcher version: 1.5.146373
Game version: 1.98.146373
Branch: main / beta branch not specified
` (stable / rc / dev)
**CBA Version:** `3.15.1` (stable / dev + commit hash)
**ZEN Version:** `1.8.0` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ZEN
- 3den_Enhanced
- CUP Terrains-Core
- CUP Terrains-Maps
- CUP Terrains-CWA
- CUP Terrains-Maps 2.0
- CUP Weapons
- CUP Units
- CUP Vehicles
- Private Military
- RHSUSAF
```

**Description:**
- When logging onto my server, I get an error stating that the Zeus Enhanced mod does not have the required key on the server. Screenshots attached. 

**Steps to reproduce:**
- Direct connecting to my server, launches the game, activates map loading screen, then receives error. 

**Where did the issue occur?**
- Dedicated Multiplayer Server hosted by myself using GTXGaming

**Additional information:**
- I used WINSCP to manage the server and add the mods directly onto the server. 

**RPT log file:**
- https://pastebin.com/0X0TkSAG

**Screenshots:**
![Error 1](https://user-images.githubusercontent.com/68551961/87949259-0dc7ea80-ca63-11ea-9946-a8316d8c12d3.png)
![Error 2](https://user-images.githubusercontent.com/68551961/87949265-0e608100-ca63-11ea-9404-78608772a035.png)

**Comment by mharis001** [comment]
Please double check your server configuration and ensure you have the ZEN 1.8.0 key in your `keys` folder.

**Comment by CreepPork** [comment]
This has to be user-error when setting up the mod for your server. As @mharis001 said, re-check your installation and the `keys` folder. The keys change with every release of ZEN.
