### ISSUE TITLE
Feature Request: Copy / Paste inventory into crate/vehicle module

### ISSUE THREAD

**Issue by 5sfgmilsim** [zen-mod/ZEN#453]
**Problem:**
Unable to copy inventory from vehicles and crates as a string of text, which can then be saved or used to paste inventory in another vehicle or crate.

**Solution you'd like:**
Add a module similar to what Achilles had where inventory could be copied and pasted into a text file.

**Alternatives you've considered:**
Achilles mod is only alternative I am aware of.  

**Additional context:**
Would be useful to have option to replace inventory, and add to inventory, when pasting inventory into a vehicle or crate.

**Comment by mharis001** [comment]
You can use the context menu to copy/paste object inventories.
