### ISSUE TITLE
Question about OWNERS in dynamic dialog

### ISSUE THREAD

**Issue by johnb432** [zen-mod/ZEN#456]
I've been trying to get this dialog to work. My intention is to call up all dead players in the "players" tab using the OWNERS:NOTITLE dialog.

`[["OWNERS:NOTITLE", [], [[], [], [call CBA_fnc_players select {!alive _x}]], false]]`

Currently it creates the dialog but doesn't filter the selection of players. I have tried added other parameters to see whether it has an effect on the dialog and currently only the tab selection when you open it up seems to work. I can type different integers into the side selection but it doesn't have an affect.

I have tried using allPlayers instead of CBA_fnc_players but it doesn't make a difference.

Am I fundamentaly misunderstanding what this dialog is supposed to do and capable of doing?
From the link below I understand it being able to take an input in the form of an array of players that you then can select from.

My question is: Can this input array be custom or is it going to take all players? I'm guessing if it's possible then I have incomplete parameters.

https://zen-mod.github.io/ZEN/#/frameworks/dynamic_dialog?id=owners-owners

**Comment by mharis001** [comment]
The owners control currently [filters dead players](https://github.com/zen-mod/ZEN/blob/master/addons/common/functions/fnc_initOwnersControl.sqf#L286).  I think it would be fine to remove that check.

The arguments for the owners control are the sides/groups/players selected by default and not the sides/groups/players available for selection.

**Comment by johnb432** [comment]
Thank you very much!
