### ISSUE TITLE
Make a leave vehicle option for Zeus

### ISSUE THREAD

**Issue by CPTMiller** [zen-mod/ZEN#457]
**Is your feature request related to a problem?**
Something I find frusterating is that there is no good way to get a specific AI to leave the vehicle. Either you need to take control of each and every single AI in order to leave the vehicle, but this makes things look kinda wonky. 

**Solution you'd like:**
A zeus module that you can click on a vehicle, deciding who leaves the vehicle either by group or induvidual.

**Alternatives you've considered:**
Non available.

**Additional context:**
N/A

**Comment by ampersand38** [comment]
You can select any number of vehicle occupants and use Ctrl + G to make them exit.

**Comment by CreepPork** [comment]
See @ampersand38's solution.
