### ISSUE TITLE
Wind speed changes not effective with ACE

### ISSUE THREAD

**Issue by fire-391** [zen-mod/ZEN#458]
**Arma 3 Version:** `x1.89`
**CBA Version:** `stable`
**ZEN Version:** `stable`
**ACE3 Version** `stable`

**Mods:**
```
- CBA_A3
- ACE3
- ZEN
```

**Description:**
With ACE 3 loaded, making adjustments to wind speed mid game via zen module causes a revert back to default value after a second or so.

**Steps to reproduce:**
- Start new editor mission
- Place player and game master module
- Start game
- Enter Zeus 
- Try to change wind speed to 120km/h

**Where did the issue occur?**
- Dedicated / Editor (Singleplayer) 

**Additional information:**
N/A

**RPT log file:**
- https://pastebin.com/tEgsMgwz

**Screenshots:**
N/A

**Comment by mharis001** [comment]
ACE wind simulation [sets the wind every second](https://github.com/acemod/ACE3/blob/master/addons/weather/functions/fnc_updateWind.sqf#L21) when enabled. Not much we can do about that. If you would like to manually control the wind, disable ACE wind simulation in the mission's settings.
