### ISSUE TITLE
I cant hit anything

### ISSUE THREAD

**Issue by Alienkiller187** [zen-mod/ZEN#463]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ZEN Version:** `1.x.x` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ZEN
```

**Description:**
When I open Zeus and click NATO or anything else the arrow does not go down and display any units or vehicle types.  The same thing is for groups, modules, or props. 

**Steps to reproduce:**
- All that is needed is open Zeus.

**Where did the issue occur?**
Editor Single player

**Additional information:**
I have around 49 mods only around 20 of which are enabled.

**RPT log file:**
I was unable to get to it

**Screenshots:**

**Comment by mharis001** [comment]
Please fill out the issue template completely. Also, please try with CBA and ZEN only.

**Comment by Pinecone227** [comment]
Do you have MCC enabled? Try without it.

**Comment by mharis001** [comment]
Closing due to incomplete issue template and conflicting information in terms of mods loaded. If the issue occurs with CBA and ZEN only, please reopen the issue.
