### ISSUE TITLE
Remove previous selection in Teleport Players module

### ISSUE THREAD

**Issue by johnb432** [zen-mod/ZEN#467]
**Is your feature request related to a problem?**
My unit and I are always frustrated when we use the "Teleport Players" module. It keeps the player selection which is not suited for a virtual zeus as you have to constantly teleport different players (disconnects, respawns, etc.).

**Solution you'd like:**
I'd like the selection to be deleted every time you open the interface or have the option to set it to that.
https://github.com/zen-mod/ZEN/blob/c91da8de613553041af0329c5c1fb5ce14efeef3/addons/modules/functions/fnc_moduleTeleportPlayers.sqf#L21
I'm guessing you would have to add "true" as a last parameter (unless that doesn't work for OWNERS).

**Alternatives you've considered:**
Using the ACE teleport module.

**Comment by mharis001** [comment]
I think this would be a reasonable change. For QOL in temrs of how the module is generally used, clearing selection should work well. Would like to have others weigh in on what the better behaviour is.

**Comment by GCrane93** [comment]
> I think this would be a reasonable change. For QOL in terms of how the module is generally used, clearing selection should work well. Would like to have others weigh in on what the better behaviour is.

If I am doing a one of teleport of a player, the context menu (V key) is, in my opinion, better - but I am in agreement that the selection should be cleared after use.

**Comment by fire-391** [comment]
^^ This. I cant say I've ever used the module the context menu is vastly superior. IMHO I think the module should be deprecated unless someone can think of a reason why the module would be better.
