### ISSUE TITLE
Paradrop Module

### ISSUE THREAD

**Issue by AlexMason1** [zen-mod/ZEN#468]
**Is your feature request related to a problem?**
Making Paradrops as Zeus is a bit tricky at the moment, I have to place the Helo with Crew in a single group and the Infantry in annother Group that I want to drop. I then have to set a movement order for the Helo Crew, make it fly on a specific height and give the Infantry a Paradrop Marker somewhere on the line where the Helo moves to.

**Solution you'd like:**
A Module which works Similar to the Ambient Flyby. Choose from a variety of Planes and Helos which are able to fit Infantry (autodetect factions and helicopters), beeing able to choose the height and the amount of Planes and Helos aswell as how many Paratroopers should be dropped (detect Passenger space in chosen vehicle) and set the Paradrop destination. Units will then Paradrop and once reached the ground regroup at the Paradrop point waiting for new orders from Zeus. Also the direction which the Plane or Helo moves can be chosen. Air Assets get deleted just like with the Ambient Flyby module.

**Alternatives you've considered:**
Just sticking with the current way to Paradrop.

**Additional context**
N/A

**Comment by mharis001** [comment]
I think what you are looking for can be achieved by using the Spawn Reinforcements module and selecting paradrop for the insertion method when an air vehicle is selected.

**Comment by AlexMason1** [comment]
Oh I never used that before. Thanks for the advice, it works really good. I will close this issue.
