### ISSUE TITLE
Double Click attributes not applying

### ISSUE THREAD

**Issue by MrJinxycake** [zen-mod/ZEN#473]
So in the server we have this running, when we double click on something... say the cryopod from OPTRE, when we change it from the basic UNSC {insert numbers here} to what ever and we push OK, nothing applies. This goes for all vehicles, ai, and players. Is there any thing i could be doing wrong?

**Comment by mharis001** [comment]
> So in the server we have this running

Just to make sure, ZEN has to installed everywhere (not just server and people using Zeus). Many attributes rely on target events to be applied.

> we change it from the basic UNSC {insert numbers here}

What do you mean by "change it"? What attribute are you changing?

**Comment by CreepPork** [comment]
Please fill out the issue template.

Also, OPTRE is known to have compatibility issues with Zeus addons.

**Comment by CreepPork** [comment]
Closed as a most likely incompatibility and no issue template.
