### ISSUE TITLE
Feature Request: Text Box

### ISSUE THREAD

**Issue by synixebrett** [zen-mod/ZEN#48]
Ares had a `CopyPaste` dialog that was a huge text box used to copy or paste text from

**Comment by mharis001** [comment]
Do you mean for the dynamic dialog (multi-line text edit with an argument to set its height?) or a specialized UI specifically for copying/pasting.

**Comment by CreepPork** [comment]
The most applicable case would be for the dynamic dialog. Ares/Achilles had it as a specialized `createDialog`.

**Comment by synixebrett** [comment]
Yes for the dynamic dialog
