### ISSUE TITLE
FR: Indicator when another Zeus is RC-ing

### ISSUE THREAD

**Issue by Quailsnap** [zen-mod/ZEN#480]
See title.
A colored circle similar to the one used to indicate player units would be nice.

BlindZeus has a custom-written stackable RemoteControl. Note that ZEN is not compatible with BlindZeus, and I have created a similar FR there, but just for inspiration:
https://github.com/Bummeri/BlindZeus/blob/master/functions/fn_moduleRemoteControl.sqf

**Comment by mharis001** [comment]
The editable object icons in Zeus are handled in engine. Don't think there is a feasible way for us to achieve this.
