### ISSUE TITLE
Feature Request: Reset/Remove Unit Gear Module

### ISSUE THREAD

**Issue by Quailsnap** [zen-mod/ZEN#484]
**Is your feature request related to a problem?**
N/A

**Solution you'd like:**
A module that can alter gear of AI/players/vehicles according to presets.
Either place on nothing, select a box of units, press [ENTER]..
.. or place over one unit. Then, options:
1. Reset Gear to Config
2. Empty Gear (Except uniform)
3. Remove Weapons & Ammo

**Alternatives you've considered:**
N/A

**Additional context:**
Not necessarily present in Achilles or elsewhere, just something I would like when I am giving players new loadouts to manually build from an Arsenal.

**Comment by mharis001** [comment]
I think this module would be too specific for inclusion into ZEN. You can use the custom module framework to easily add it for your purposes.
