### ISSUE TITLE
Zeus Enhanced Causing Steam STATUS_ACCESS_VIOLATION Reports when Starting Arma 3

### ISSUE THREAD

**Issue by Iwillkillyou178** [zen-mod/ZEN#486]
**Arma 3 Version:** `2.01.146887` (dev)
**CBA Version:** `3.15.1` (stable)
**ZEN Version:** `1.9.0` (stable)

**Mods:**
```
- CBA_A3
- ZEN
```

**Description:**
- When I am starting up Arma 3 from the Launcher, it processes the mod-list and then goes to the Arma 3 Screen briefly for a few seconds before crashing back to desktop, with the 0xC0000005 - STATUS_ACCESS_VIOLATION Error Popup. When I started Arma 3 without mods it worked fine, so then I started going through my modlist to find the culprit, breaking them up into groups, and then breaking down the group of mods that didn't work to find the mod that was bugged, and it turned out to be Zeus Enhanced. 

**Steps to reproduce:**
- Simply start up Arma 3 on my Dev Version with CBA and Zeus Enhanced, 

**Where did the issue occur?**
- Starting up the Arma 3 Launcher

**Additional information:**
- Running Zeus Enhanced alone with CBA produced the same problem, it doesn't seem to be other mods, running any of my mod presets without Zeus Enhanced has them running fine with no issues. It might be a corrupted mod file, but when I delated the Zeus Enhanced Mod Folder in *!Workshop* Folder in the *Arma 3* Files Directory and then unsubscribed and re-subscribed to the mod, the same issue still occurs.

**RPT log file:**
- [Arma 3 Iwill RPT Log File.zip](https://github.com/zen-mod/ZEN/files/5503743/Arma.3.Iwill.RPT.Log.File.zip)

**Screenshots:**
![Screenshot (148)](https://user-images.githubusercontent.com/74074060/98418266-7eb20300-2050-11eb-881d-09d5d17700cf.png)
![Screenshot (149)](https://user-images.githubusercontent.com/74074060/98418274-82de2080-2050-11eb-9b78-210ae15e0b5f.png)
![Screenshot (150)](https://user-images.githubusercontent.com/74074060/98418281-84a7e400-2050-11eb-8310-eb1b43571e09.png)

**Comment by neilzar** [comment]
Could you try without GM? See if that narrows it down a bit more as I don't see any issue in the RPT.

**Comment by Iwillkillyou178** [comment]
I just tried running it without Global Mobilization, same event occurred, I also tried running it *with* the Contact DLC Loaded to see if that was the culprit somehow, no difference. Here's the RPT file for the run with no other mods besides CBA and Zeus Enhanced, and no Addon DLC (No GM or Contact).
[Arma 3 Iwill RPT Log File #2.zip](https://github.com/zen-mod/ZEN/files/5503976/Arma.3.Iwill.RPT.Log.File.2.zip)

**Comment by mharis001** [comment]
Does the issue occur on stable Arma 3? Could just be some instability with dev branch.

**Comment by Iwillkillyou178** [comment]
Yes it is the Development Branch, on the Stable Branch it works fine as it turns out, something must have changed in Development in the past week or two.

**Comment by veteran29** [comment]
Maybe @Dedmen can help here.

**Comment by mharis001** [comment]
Closing as likely just dev branch instability. Don't think it is anything on ZEN's side.
