### ISSUE TITLE
Feature Request: Heal module

### ISSUE THREAD

**Issue by FrostKota** [zen-mod/ZEN#488]
**Is your feature request related to a problem?**
No but it would make things a bit easier with the current healing in place in Zeus Enhanced and streamlined.

**Solution you'd like:**
Adding in a healing module that was in Achilles, that allowed you to fully heal players and/or AI whether you're playing vanilla or modded Arma 3 with mods such as ACE. The module could be placed on just a single unit like the current heal in Zeus Enhanced or if needed be placed on the ground instead and by using the "selection box" that you get when holding left click on the mouse and highlighting units or groups that you wish to heal or even just holding CTRL+LMB to pick multiple specific individuals that you would like to heal and then pressing a key like enter to activate the heal. This healing module can make it easier for healing large groups of players or AI in a timely manner because Arma 3 can be very weird and have incidents and using the current heal would take a little bit more time to always have to click on each individual manually.

**Alternatives you've considered:**
If not adding another type of healing module, modifying the current one to be able to place on the ground rather than needing to be placed on a unit and to allow the zeus to pick with either CTRL+LMB or selecting groups by highlighting them with the selection box with the heal and pressing enter to activate the heal.

**Additional context:**
Achilles mod for reference on the healing module, I've been told that the people who made Achilles are making Zeus Enhanced so I believe the developers of Zeus Enhanced may already know or remember this feature.

**Comment by TheRadiumDude** [comment]
There is already a **Heal** option on the context menu which can do what you're asking for. Please do correct me if I'm wrong and misunderstanding what you meant.

**Comment by FrostKota** [comment]
> There is already a **Heal** option on the context menu which can do what you're asking for. Please do correct me if I'm wrong and misunderstanding what you meant.
> 
> The **Heal** option heals everything in your selection, might I add.

So I found the option in the context menu I believe you're referencing, though for the "***Heal*** option" that heals everything in my selection are you talking about the one under Misc in the Zeus bar? and if so how do you get it to work?



![Heal](https://user-images.githubusercontent.com/74566183/99354038-b05a7380-2873-11eb-8692-29f35ad2416e.PNG)

**Comment by TheRadiumDude** [comment]
No, I believe that module is reserved just to heal single units. However, it is vastly quicker to just use the context menu action. As the issue has been closed, if you have any more questions that don't warrant making a GitHub issue, come join our support Discord [here](https://discord.gg/vSSyghh).
