### ISSUE TITLE
Editing a remote controlled units inventory breaks RC

### ISSUE THREAD

**Issue by tyl3r99** [zen-mod/ZEN#489]
**Arma 3 Version**: 2.00 (stable)
**CBA Version**: 3.15.2.201119 (stable)
**ZEN Version**: 1.9.0 (stable)

**Mods:**
- CBA_A3
- ZEN
- ZEUS CACHE
- RHS USAF, AFRF, GREF
- TFAR BETA
- ACE
- VCOM 3.4.0
- PROJECT OPFOR
- ENHANCED MOVEMENT
- SPLENDID SMOKE

**Description:**

> When myself and my friend were co zeusing a mission for our group we encountered a pretty severe bug. 
> when i remote controlled a unit and asked my friend to give me a weapon (I think rangefinder in this case) 
> I could tell when he accessed my unit as my guy froze. Anyway.. when he said ok done my guy was frozen and could not control him anymore. 
> 
> After exiting the remote control of that specific unit, any unit I tried to RC would not fully get taken over. Instead they proceed to have full control with movement and firing. 
> 
> I then decided to leave the server and re join. When I re joined I lost all Zeus capabilities. 
> I would also like to add that as soon as we promoted eachother zeus as it happened to both of us at different times of the mission. ZEUS UI LOCKUP happened from then onward. 
> 
> Its linked to getting zeus while in game I think.

**Add the steps needed to reproduce the issue.**

> Get 1 to RC a opfor unit and get the other zeus to edit inventory and give him a rangefinder or something and then back out of it releasing him.

**Where did the issue occur?**

> On a Dedicated Server (Stable exe)

**Additional information:** 

> - Neither of us was on Profiling branch

- 

**Provide any additional information that will help us solve this issue.
RPT log file:** 

> Unfortunately I was unable to locate the rpt since we have done multiple missions since. 

**### Original post below.**

When 2 people are zeusing 

Get 1 to RC a opfor unit and get the other zeus to edit inventory and give him a launcher or something and then back out of it releasing him. 

His unit will lockup and whenever he tries to RC a unit afterwards he cannot control them. He has to leave the server and re join. Even after doing so his zeus then does not work at all.

**Comment by tyl3r99** [comment]
Latest version of zen and cba to date 
30/11/20

**Comment by tyl3r99** [comment]
Last bit 

Mods used in addition are 
ACE 
TFAR
Rhs usaf afrf gref 

I am not using ace zen compat

**Comment by TheRadiumDude** [comment]
Please edit your original message and fill out the issue template.

**Comment by tyl3r99** [comment]
I will do it next time I report a bug 
It didn't come up this time for some reason it was blank but I've provided all the necessary info. 

I checked RPT nothing was on it error wise

**Comment by tyl3r99** [comment]
If they put the template into the "report issue" it would be easier lol
But okay have you got a link to this "template"

**Comment by TheRadiumDude** [comment]
When you create a **New Issue**, you usually can select a template, like **Bug Report** or **Feature Request**. The template should be ready to be filled out like follows:

> **Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ZEN Version:** `1.x.x` (stable / dev + commit hash)
>
>**Mods:**
>```
>- CBA_A3
>- ZEN
>```
>**Description:**
>- Add a detailed description of the error. This makes it easier for us to fix the issue.
>
>**Steps to reproduce:**
>- Add the steps needed to reproduce the issue.
>
>**Where did the issue occur?**
>- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal
>
>**Additional information:**
>- Provide any additional information that will help us solve this issue.
>
>**RPT log file:**
>- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An >instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).
>
>**Screenshots:**
>If applicable, add screenshots to help explain your problem.

**Comment by tyl3r99** [comment]
Ok will do in future

**Comment by CreepPork** [comment]
@tyl3r99 Don't do this only in the future, do it for this issue too. This is critical information for us to understand. As @TheRadiumDude said, please edit your issue with the filled out template.

**Comment by tyl3r99** [comment]
Ok when I'm home from work I will convert it

**Comment by tyl3r99** [comment]
Original post updated.

**Comment by TheRadiumDude** [comment]
Can you reproduce this same issue with just `ZEN` and `CBA_A3` enabled?

**Comment by mharis001** [comment]
Can reproduce. Happens because ACE Arsenal requires units to be local and achieves that by remote controlling the unit. I wonder if this is the cause of the UI lockup bug as well.

I think we have to remove opening arsenal on currently remote controlled units and other players. Not much we can do if the arsenals themselves don't support remote units.

**Comment by BrettMayson** [comment]
Can you create a bug report in ACE and tagged me? I can take a stab a fix over the holidays
