### ISSUE TITLE
Is there a way of backing up custom compositions created with ZEN? Where are they saved?

### ISSUE THREAD

**Issue by Pinecone227** [zen-mod/ZEN#495]
I've used the custom composition feature extensively to basically create several new factions from scratch. It recently dawned on me that I don't know how to create a backup of my hours and hours of work in case there was a equipment failure or if I simply wanted to move to a different machine. So my question is: Where, or within what file are they stored? I imagined that they could be somewhere in the profile but had no luck finding anything corresponding to the compositions.

**Comment by mharis001** [comment]
They are saved to your Arma 3 profile (`profileNamespace`). You could copy the file to somewhere else to back them up.

Alternatively, you could extract the data using:

```sqf
profileNamespace getVariable ["zen_compositions_data", []];
```

and then set them to another profile using:

```sqf
profileNamespace setVariable ["zen_compositions_data", <composition_data>];
```
Hope that helps.

**Comment by Pinecone227** [comment]
Thank you, I was able to save the data to a text file. Closing issue.

**Comment by oOKexOo** [comment]
Btw. if you want to back up your entire profile.
`%UserProfile%/Documents/Arma 3` or `%UserProfile%/Documents/Arma 3 - Other Profiles` should contain a folder of your profiles. The folder contains everything from variables saved via `profileNamespace` (`*.vars.Arma3Profile`) to Eden compositions (`compositions` folder).

**Comment by Pinecone227** [comment]
Yeah, I've done profile backups before and guessed that would work aswell but my main focus here was just the ZEN custom compositions. Thanks though.
