### ISSUE TITLE
Feature Request: Area of Operations (Cover Map module)

### ISSUE THREAD

**Issue by CreepPork** [zen-mod/ZEN#523]
**Is your feature request related to a problem?**
Now, that the Area Markers exist in ZEN, it would be nice if this was extended to allow drawing of the [Cover Map module](https://community.bistudio.com/wiki/BIS_fnc_moduleCoverMap) on the map.

**Solution you'd like:**
A module that when placed, prompts you to draw the AO of your operation, resembling the Area Markers module from ZEN.

**Alternatives you've considered:**
Using variables found in the BI documentation but that is time-consuming and I typically don't setup a mission template before hand in Eden, so having this in Zeus would be nice and quick.

**Comment by mharis001** [comment]
A module that opens a dialog with a map control that allows users to select an area by clicking and dragging on the map could work. I think it would be difficult to try to integrate this into the Zeus display's map. The dialog could also have an option to remove markers that are covering the map.
