### ISSUE TITLE
Add Editable Objects doesn't add mines

### ISSUE THREAD

**Issue by irvnriir** [zen-mod/ZEN#529]

**Comment by mharis001** [comment]
Not possible since curator editable objects don't support mines directly. This is why mines in the create trees use a helper module to which the mine is attached.

**Comment by irvnriir** [comment]
@mharis001 this can be solved by replacing the mines with spawned by Zeus functions .

**Comment by mharis001** [comment]
I guess but not a fan of that solution overall.
