### ISSUE TITLE
zeus enhanced doesn't show some of my mods assets in the empty faction

### ISSUE THREAD

**Issue by kripto202** [zen-mod/ZEN#530]
**Arma 3 Version:** `stable` (stable / rc / dev)
**CBA Version:** `stable` (stable / dev + commit hash)
**ZEN Version:** `stable` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- zeus enhanced
- ace
- task force radio
- optre
- namenai script mod
- legion base - stable
- kobra mod pack - main
- imperial studio
- enhanced movement
- zeus enhanced - ace3 compatibility
- 3den enhanced
```

**Description:**
- In zeus I am trying to find my assets for the kobra mod pack and imperial studio mods in the empty (yellow) faction. Everything looks fine in terms of having everything work and in blufor and opfor, they work perfectly. With achillies, everything works fine.

**Steps to reproduce:**
- place a default blufor unit
- place a game master module with '#adminlogged' and use official and unoffical addons
- go to the empty faction
- don't find imperial studio and kobra categories

**Where did the issue occur?**
- all forms of usage in zeus

**Additional information:**
- I tried to look over other mods that were working and there doesn't seem to be anything different to what I have done to ensure it shows in zeus.

**Screenshots:**
https://cdn.discordapp.com/attachments/490973894421905438/803724290826436658/unknown.png
https://cdn.discordapp.com/attachments/490973894421905438/803724576097828884/unknown.png
https://cdn.discordapp.com/attachments/490973894421905438/803724877114245211/unknown.png

**Comment by kripto202** [comment]
I'm certain it has something to do with my config not working with zeus enhanced in some way but I can't figure out why.

**Comment by mharis001** [comment]
The "Declutter Empty Tree" setting removes empty vehicles from the create units empty tree since they can be placed through the side create trees by unchecking include crew checkbox. Can you try disabling that setting and seeing if the issue persists?

**Comment by kripto202** [comment]
ya that seems to work, what would be the cause of it?

**Comment by mharis001** [comment]
There is no issue then. The setting exists to mimic 3DEN's behaviour of not including faction vehicles in the props tree.

**Comment by kripto202** [comment]
Then what would i need to fix this issue so people don't need to turn off that setting?

**Comment by mharis001** [comment]
I think I better understand your situation now. Are you using the same `displayName` for `CfgFactionClasses` and `CfgEditorCategories`?

**Comment by kripto202** [comment]
no

**Comment by kripto202** [comment]
![image](https://user-images.githubusercontent.com/8568526/105911978-c8c7d680-5ff8-11eb-8c84-4734471e8b1c.png)
you mean like this?

**Comment by kripto202** [comment]
yup that was the cause.

**Comment by mharis001** [comment]
Yeah, the current code assumes that there won't be name clashes like that. I think we have can either:

1. Not remove nodes whose text is also a `CfgEditorCategories` class.
2. Process the tree at the object node level and see if the class is a vehicle or prop.

I am leaning towards option 1 since I think checking each object node would significantly impact the display's load time and this situation is pretty rare.
