### ISSUE TITLE
How to export custom compositions ?

### ISSUE THREAD

**Issue by irvnriir** [zen-mod/ZEN#533]
I use them to store Groups, vehicles with custom cargo and such . Without the ability to export, i risk loosing a lot of time that i've spend on the naming and sorting .

**Comment by mharis001** [comment]
Custom compositions are saved to `profileNamespace` under the variable `zen_compositions_data`.

You can get your composition data using:

```sqf
profileNamespace getVariable ["zen_compositions_data", []];
```

And set it using:

```sqf
profileNamespace setVariable ["zen_compositions_data", _data];
```

**Comment by CreepPork** [comment]
I think this has been raised again and again and maybe a designated button for export and import should be implemented.

**Comment by neilzar** [comment]
Closing this in favour of the better-detailed #550

**Comment by irvnriir** [comment]
when i try to load items with mannable objects, (only) they break the menu (it shows like there is none), here is the export of them : [format_sqfArray.txt](https://github.com/zen-mod/ZEN/files/6039905/format_sqfArray.txt) ;

i tried to export multiple times and load before formatting . they was completely mixed with working ones (without vehicles) .

also , when i try to spawn loaded ones with Independent Units , the Units is not spawned (but objects is) . here is an example : [t.txt](https://github.com/zen-mod/ZEN/files/6039992/t.txt) ;

**Comment by irvnriir** [comment]
Here is a few related scripts, just if anyone may find useful .

(of course its better to manage (and share) them as arrays in-game)

```
//### customCompositions_zeusEnhanced

	//Get from multiple files, merge, load . If executed Globally, allow to specify the player .
		//[profileNameSteam,"west","east","independent","sideEmpty","civilian"] call act_load_CC_ZEN;
		act_load_CC_ZEN = {
			[] call act_save_CC_ZEN;
			_v1_s = _this select 0;
			_this = +_this;
			_this deleteAt 0;
			_v_s = [];
			{
				_v = "storage\modded_rp_zeus\CC_ZEN\"+_x+".sqf";		//bug
				_v = ([nil] apply {[] call compile preprocessFileLineNumbers (_v)}) select 0;
				if !(isNil "_v") then{
					_v_s = _v_s + _v;
				};
			}foreach _this;
			if (profileNameSteam == _v1_s) then{
				profileNamespace setVariable ["zen_compositions_data", _v_s];
				systemChat "loaded Custom Compositions";
			};
		};

	//Get, sort and save as Output and to clipboard . Then the save can be formatted as JSON or other .
		//[] call act_save_CC_ZEN;
		act_save_CC_ZEN = {
			_v_s = profileNamespace getVariable ["zen_compositions_data", []];
			_g_s = []; _nu = 0;
			_nu_s = 0; _nu1_s = count _v_s;
			while {_nu_s < _nu1_s} do{
				_v1_s = _v_s select _nu_s;
				_v = _v1_s select 0;
				_nu = -1;
				{if (_x select 0 == _v) exitWith{_nu = _forEachIndex;};}foreach _g_s;
				if (_nu == -1) then{
					_nu = _g_s pushBack [_v,[]];
					
					//# Arma3 . [d act_sel act, in Sort]
					_g_s sort true;
					{if (_x select 0 == _v) exitWith{_nu = _forEachIndex;};}foreach _g_s;
				};
				_g_s select _nu select 1 pushBack _v1_s;
			_nu_s = _nu_s + 1; };
			_g = [];
			{_g = _g + (_x select 1);}foreach _g_s;
			
			copyToClipboard str _g;
			systemChat "saved Custom Compositions to clipboard";

			_g
		};
```
