### ISSUE TITLE
Open Custom Compositions by default

### ISSUE THREAD

**Issue by irvnriir** [zen-mod/ZEN#540]
They are a way to save presets of and just sort, everything . (boxes, units, factions, etc)

As more accessible they are so better . plz make at least the "Custom" level unfolded by default . Also, auto switching to their interface on openCuratorInterface would be helpful .

**Comment by mharis001** [comment]
I don't think this is something that will be implemented. The tree can be easily expanded using the expand all button. For most people, restoring the create trees to the previous mode/side is preferable over always opening into empty compositions.

**Comment by irvnriir** [comment]
@mharis001 Oh, it does restore empty . I have a weird bug so it switches between Opfor / Blufor each time (if they was on close) .

The main suggestion is to unfold it, "at least Custom" . but restoring the foldings could be good too . Expand All is mostly useless here .

**Comment by mharis001** [comment]
Switching between BLUFOR and OPFOR sides is a base game bug in the `RscDisplayCurator` script. There isn't really a good way for us to fix that.

**Comment by irvnriir** [comment]
Its not an issue, just i missed that empty reopens properly .

>The main suggestion is to unfold it, "at least Custom", but restoring the foldings could be good too . Expand All is mostly useless here .

?
