### ISSUE TITLE
BIS_fnc_curatorObjectEdited conflict

### ISSUE THREAD

**Issue by IvosHcz** [zen-mod/ZEN#551]
There is a conflict with BIS_fnc_curatorObjectEdited

Scenario: warmachine
(discord https://discord.gg/QsHcJR7)

Reproduction 3DEN:
- place player
- place curator module, name it z1, owner #adminlogged
- run the code

Code:
```
	vehArti = createVehicle ["B_MBT_01_arty_F", [getPos player select 0, getPos player select 1, 50], [], 0, "NONE"];
	createVehicleCrew vehArti;
	z1 addCuratorEditableObjects [[vehArti],true];
	[objNull, vehArti] call BIS_fnc_curatorObjectEdited;
```
screenshot:
https://cdn.discordapp.com/attachments/768200800391659530/810153937863835678/107410_20210213172142_1.png

**Comment by neilzar** [comment]
Why are you running that function, though? It is no supposed to be used like that.

**Comment by IvosHcz** [comment]
I spawn vehicle in the game if team captures objective. Simulates airdrop and then is available to ZEUS

**Comment by IvosHcz** [comment]
At dicrod you can download the mission file for EDITOR

**Comment by neilzar** [comment]
As I said though, the function is not supposed to be used like that. It is an internal function for the edited event handler. There is code in there, specifically the part where you get an error, that requires it to be run from the interface of the Zeus that edited the object at the moment it was edited.

You'll have to find another function to simulate an airdrop.

**Comment by IvosHcz** [comment]
Thank you
