### ISSUE TITLE
Execute Code Global not working.

### ISSUE THREAD

**Issue by M829A3** [zen-mod/ZEN#559]
**Arma 3 Version:** `2.00` (stable)
**CBA Version:** `3.15.1` (stable)
**ZEN Version:** `1.10.0` (stable)

**Mods:**
```
- CBA_A3
- ZEN
- Zeus Enhanced - ACE3 Compatibility
```

**Description:**
Execute Code Global not working.I execute [west, "HQ"] sideChat "Check" but only Zeus can see the text.

**Expected behavior:**
Everyone can see the text.

**Steps to reproduce:**
Add the steps needed to reproduce the issue.

1. _Go to Development Tools
2. _Click Execute Code

**Where did the issue occur?**
- Dedicated

**Additional information:**
Server load the ZEN and ACE3 Compatibility mod.

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

**Screenshots:**

**Comment by mharis001** [comment]
Just to confirm, is ZEN installed everywhere (server and all clients)?

**Comment by M829A3** [comment]
> Just to confirm, is ZEN installed everywhere (server and all clients)?

Not every clients,server installed

**Comment by mharis001** [comment]
That is the problem then. The Execute Code module uses a global event for the global execute. ZEN has to be installed on all machines.

**Comment by M829A3** [comment]
> That is the problem then. The Execute Code module uses a global event for the global execute. ZEN has to be installed on all machines.

I can't ask every player installed ZEN......Why Achilles can use global execute without this limit......

**Comment by neilzar** [comment]
Because they work differently, they are not the same mod and were not designed the same way.
