### ISSUE TITLE
View animations

### ISSUE THREAD

**Issue by martuksxxxx** [zen-mod/ZEN#561]
I am pretty sure Archilles had this feature, this is Animation viewer. Simple as that. (The one we have in eden, where you can check all animations ingame)

**Comment by TheRadiumDude** [comment]
Can you fill out the Issue Template fully and explain why this would be a good feature to have? I personally can't see a use-case.

**Comment by Pinecone227** [comment]
This is a debug console feature, ZEN doesn't require this functionality, you can simply add the console to your mission and access the animation viewer on the fly that way.
