### ISSUE TITLE
[Feature Request] Compatibility add-on for MCC Sandbox 4

### ISSUE THREAD

**Issue by onlyzahj** [zen-mod/ZEN#573]
**Is your feature request related to a problem?**
This feature request is only related to my personal problem. The Assign AI to Zone feature of MCC Sandbox 4 is something I have to use frequently, however it takes way too many clicks when it can be done is so few.

**Solution you'd like:**
I'd like to request a Compatibility addon for MCC that allows Zeus the ability to right click on an AI or an AI Group and have an option for MCC > Assign AI to zone. When selected, this option would pop up the standard dialog box that already exists for the user/Zeus to select the Zone and the AI Behavior. That's it.

**Alternatives you've considered:**
Sucking it up and using the existing, time sucking, MCC Module.

**Additional context:**
The current ZEN right click menu I would like this feature to be added to: [Image 1](https://i.gyazo.com/a9eb004d94d6330279184dc9fb1a300c.png)
The MCC Sandbox 4 module: [Image 2](https://i.gyazo.com/d928ae7d278f79d57f9be0b619d6f904.png)
The Dialog Box that opens when the existing module is used: [Image 3](https://i.gyazo.com/1bbd97b32d905ecea1f324723a073b35.png)

**Comment by mharis001** [comment]
I think this is too specific for ZEN. Generally, we only provide direct support for ACE3. However, you can add your own context menu actions using the [context menu framework](https://zen-mod.github.io/ZEN/#/frameworks/context_menu).
