### ISSUE TITLE
Arma 3 Steam Workshop Doesn't Download the Mod

### ISSUE THREAD

**Issue by Water261** [zen-mod/ZEN#581]
**Arma 3 Version:** `2.02.147359` stable 
**CBA Version:** ` 3.15.1` stable
**ZEN Version:** `1.10.0` stable

**Mods:**
```
- CBA_A3
- ZEN
- ACE
- Tier One Weapons
- RHSUSAF
- GGE: Weapon Swap
- ACE Compat - RHS United States Armed Forces
```

**Description:**
Steam workshop doesn't download the mod, comes up as corrupted since the folder is empty

**Expected behavior:**
The latest steam workshop version of ZEN to be installed

**Steps to reproduce:**
Add the steps needed to reproduce the issue.

1. Go to the steam workshop page for Zen
2. Click download
3. Look inside the Arma 3 Launcher, Mod should be marked with an Exclamation Mark

**Where did the issue occur?**
- Launcher

**Additional information:**
Latest Release from Github Works
**EDIT:** It seems repairing the mod does actually download the files.

**RPT log file:**
N/A

**Screenshots:**
![image](https://user-images.githubusercontent.com/48581492/114126490-e0e29d00-993b-11eb-81bf-1fa43ab32416.png)
![image](https://user-images.githubusercontent.com/48581492/114126515-ea6c0500-993b-11eb-9aaf-f6bc1dfd202d.png)

**Comment by CreepPork** [comment]
This is not ZEN's fault. Try repairing the installation in the Arma 3 Launcher.
