### ISSUE TITLE
Hide enemy Unit markers / Fold enemy groups in list

### ISSUE THREAD

**Issue by irvnriir** [zen-mod/ZEN#588]
**Is your feature request related to a problem?**
Zeus/-es in my games always want to play too X) , but the Unit markers give too much information 

**Solution you'd like:**
A setting to, on interface open, in left list -- fold groups of certain sides . The perfect would be also to randomize within radius, the group markers' position, and maybe hide the Objects, but thats maybe too much work .

**Alternatives you've considered:**
Map commanding interfaces require to process/analyze the map info about terrain, that is too much when the game is played while thinking about other things .

**Comment by mharis001** [comment]
I believe this request is too specific for inclusion in ZEN. If you want to hide all editable object icons, there is the "Toggle Editable Icons" keybind. Additionally, the icons are handled in engine and can't really be controlled using SQF.

**Comment by irvnriir** [comment]
@mharis001 im sure the Controls/list can be controlled with SQF, the keybind require much more additional work to be helpfull .

**Comment by mharis001** [comment]
Yes, you can modify the entities tree but the icons themselves cannot be modified. If all you want to do is collapse nodes for groups of a certain side, that is doable. However, I believe it is too specific for inclusion into ZEN.
