### ISSUE TITLE
modules are non functioning 

### ISSUE THREAD

**Issue by iceball117** [zen-mod/ZEN#591]
after the install of the mod and command line changes the modules wont function in the Zeus game. even after bringing the server back to almost nothing it still dose wont function. 

**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ZEN Version:** `1.x.x` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ZEN
```

**Description:**
Add a detailed description of the error. This makes it easier for us to fix the issue.

**Expected behavior:**

**Steps to reproduce:**
Add the steps needed to reproduce the issue.

1. _Go to ..._
2. _Click ..._
3. _See ..._

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Additional information:**
Provide any additional information that will help us solve this issue.

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

**Screenshots:**

**Comment by mharis001** [comment]
Can't reproduce. Working as expected for me. Please completely fill in the issue template and provide an RPT file.
