### ISSUE TITLE
Allow lerped weather change instead of only immediate

### ISSUE THREAD

**Issue by IR0NSIGHT** [zen-mod/ZEN#596]
**Is your enhancement related to a problem?**
The weather change module does not allow a lerped/smooth weather change. Weather changes are immediate and harsh (immersion breaking).
(We switched from Achilles to ZEN, and this is a module that ZEN doesnt have yet)

**Solution you'd like:**
Weather change spaced out over a couple minutes. Basically 1:1 copy achilles weather change:
https://github.com/ArmaAchilles/Achilles/blob/master/%40AresModAchillesExpansion/addons/modules_f_achilles/Environment/functions/fn_EnvironmentSetWeatherModule.sqf

**Alternatives you've considered:**
Achilles. But thats a. legacy b. doesnt offer everything ZEN offers c. has some compat issues running alongside ZEN (deep copy of units ctrl shift c/v runs copy for achilles AND zen, leading to collision)

Scripts: not user friendly enough.

**Comment by TheRadiumDude** [comment]
There is already an option to change it to a 'smooth' transition *(disable force change)*, but this happens via the vanilla weather engine so you can expect some potential desync. I'm closing the issue and marking as Invalid, but please do let me know if you were referring to another possible enhancement.
