### ISSUE TITLE
Supplies(Ace mortar ammo crates and etc.), modules and factions disappear in singleplayer and editor

### ISSUE THREAD

**Issue by maximmmmichael3** [zen-mod/ZEN#597]
**Arma 3 Version:** `2.04.147719` stable
**CBA Version:** `3.15.3` stable
**ZEN Version:** `1.10.0` stable

Mods:
```
- CBA_A3
- ZEN
- ZEN Ace 3 compatibility
- Ace 3
- Chemical Warfare Heal
- WW1 MOD - REMEMBRANCE 11th november (2019 tank update)
- CUP Terrains - Core
- CUP Terrains - Maps
- European_buildings
- IFA3_AIO_LITE
- Advanced Train Simulator (ATS)
- CBA_A3
```

**Description:**
I played with zeus to train in ace and other mods, but then I saw that there are no ace mortar ammo crates and ace logistic, in modules tab, it was almost completely clear, like there were no ace modules, no Chemical warfare and others, then I looked into faction tab, some of the factions were deleted.

**Expected behavior:**
I through they wouldn't disappear

**Steps to reproduce:**
1. Open Editor and place any unit
2. Make him able to become zeus
3. Start the game and open zeus
4. Open modules tab(Or factions)

**Where did the issue occur?**
- Singleplayer
- Editor (Singleplayer)

**Additional information:**
I played vanilla zeus and Chemical warfare and Ace were there, same goes with Ace logistics and factions.

**RPT log file:**
None available

**Screenshots:**
No screenshots available

**Comment by mharis001** [comment]
Do you have "All addons (including unofficial ones)" selected in the Game Master module?

**Comment by maximmmmichael3** [comment]
Thanks, it fixed the problem, but what about zeus that being spawned by mods? Like MCC, AIO command menu and etc?

**Comment by mharis001** [comment]
That would be an issue with those mods not adding all addons to the Game Master modules they create.
