### ISSUE TITLE
Placing a module from the "Recent" tab doesn't work

### ISSUE THREAD

**Issue by johnb432** [zen-mod/ZEN#603]
**Arma 3 Version:** `2.04` profiling
**CBA Version:** `3.15.3` stable
**ZEN Version:** `1.11.0` stable

**Mods:**
```
- CBA_A3
- ZEN
- ACE3 (optional)
- ZEN - ACE3 Compat (optional)
```

**Description:**
When using a module from the "Recent" section, you can't place it.
I tested initially with both ACE3 and its compat loaded (see RPT), but I have also tested without them and it produces the same result.

**Expected behavior:**
To be able to use a module from the "Recent" section. It worked prior to 1.11.0 (at least I'm pretty sure of it).

**Steps to reproduce:**
1. Create a mission with a Zeus.
2. Place down any module when in Zeus. I used the "Zeus Lightning Bolt", as you don't have to enter anything, but any other module will do.
3. Go to the "Recent" section and try to use module from there again.

**Where did the issue occur?**
- Editor (Multiplayer) / ACE Arsenal

**RPT log file:**
- [Pastebin](https://pastebin.com/mxvkEBkK)

**Comment by johnb432** [comment]
Upon further investigation it looks like to be a specific problem to the profiling branch.
Sorry for wasting your time.

**Comment by mharis001** [comment]
No worries.
