### ISSUE TITLE
Re-implement Achilles "AI Throw Smoke" Keybind

### ISSUE THREAD

**Issue by Quailsnap** [zen-mod/ZEN#609]
**Is your feature request related to a problem?**
Common use-case with Achilles is having AI throw smoke to conceal maneuvers/fire.

**Solution you'd like:**
Current CTRL+C countermeasure key only applies to vehicles as discussed in #129. While I would prefer it simply be a "deploy smoke / countermeasures" button for both vehicles and infantry (ie: would make infantry throw smoke if they have it), I understand if the ZEN team prefers it simply be for vehicles. C could work, then, as a "Throw smoke grenade" key.

**Alternatives you've considered:**
N/A

**Additional context:**
Code Achilles used: https://github.com/ArmaAchilles/Achilles/blob/f123656459cab7766aa40c32d5ee12d29ebadaae/%40AresModAchillesExpansion/addons/functions_f_achilles/functions/features/fn_LaunchCM.sqf#L33

**Comment by mharis001** [comment]
#132 will allow Zeus to make AI throw any grenade type.
