### ISSUE TITLE
Re-implement Achilles Mass Disable Simulation

### ISSUE THREAD

**Issue by Quailsnap** [zen-mod/ZEN#610]
**Is your feature request related to a problem?**
Achilles made it very convenient to turn off simulation to props en-masse with their disable simulation module: one would place it down, then highlight the props needing disabling, then press [ENTER]. ZEN means I have to disable every prop one-by-one.

Usually I use this to spawn in large compositions and then disable the simulation on buildings I do not want simulated.

**Solution you'd like:**
Re-implement old Achilles functionality, especially being able to select groups of objects.

**Alternatives you've considered:**
N/A

**Additional context:**
See: https://github.com/ArmaAchilles/Achilles/blob/f123656459cab7766aa40c32d5ee12d29ebadaae/%40AresModAchillesExpansion/addons/modules_f_achilles/Objects/functions/fn_ObjectsToggleSimulation.sqf

**Comment by TheRadiumDude** [comment]
Hello!

You should be able to do this by selecting all units, opening their attributes menu and disabling simulation via the menu there. This should apply the simulation to all selected units. Does this help the issue?

**Comment by Quailsnap** [comment]
You're correct! It completely fixes the issue, and apologies for the lack of knowledge.
