### ISSUE TITLE
ZEN_Dialog drawn under some UI elements in 3den, Dialog does not lock camera scrolling

### ISSUE THREAD

**Issue by Seb105** [zen-mod/ZEN#615]
**Mods:**
```
- CBA_A3
- ZEN
- RHS
- Eden Enhanced
```

**Description:**
ZEN Dialogs are sometimes drawn under UI elements in Eden
Also, when ZEN Dialogs are open in Eden then scrolling on listboxes also scrolls the camera, which is non-breaking but annoying

**Expected behavior:**
Draw the ZEN Dialog over these things. Lock camera scrolling whilst a dialog is open and the mouse is over the dialog

**Steps to reproduce:**
1. In 3den, place some units
2. Spawn a ZEN Dialog listbox
3. See that the unit icons are drawn over the dialog
4. Scroll on the listbox and see the camera also moves

**Where did the issue occur?**
-Editor (Singleplayer)

**Screenshots:**
![20210715171116_1](https://user-images.githubusercontent.com/65898127/125822112-0655c962-d174-429d-b67a-7071362fd3a3.jpg)

**Comment by neilzar** [comment]
ZEN is not designed to be used in 3den, it is named **Zeus** Enhanced after all. We will not support anything in 3den either, so closing this issue.

**Comment by mharis001** [comment]
While ZEN is a Zeus focused mod, fixing this issue is relatively simple and would extend the dialog framework's possibilities.
