### ISSUE TITLE
Feature: Icons while in AI Mode

### ISSUE THREAD

**Issue by Longshot133** [zen-mod/ZEN#619]
**Is your feature request related to a problem?**
Whenever in AI with players at a distance it can be difficult to tell how close and where they are.

**Solution you'd like:**
It would be cool if we had a setting to see a small icon over players heads to tell where they are and what should be done.

**Alternatives you've considered:**
There are alternative mods that can do this like the client side mod that shows FPS for zeus but a built in once would be nice.
or I can just get better and not be dumb XD

**Additional context:**

**Comment by mharis001** [comment]
I don't fully understand what you are requesting. By "AI Mode"/"in AI" do you mean remote control? Drawing icons for players while remote controlling seems too specific for inclusion in ZEN.

**Comment by Longshot133** [comment]
all good, was just a thought.
