### ISSUE TITLE
Improve the Firesupport Modul

### ISSUE THREAD

**Issue by Nilia119** [zen-mod/ZEN#628]
**Is your enhancement related to a problem?**
It is not really a Problem but it kinda bugs me. If you use the Firesupport Modul on an BM-21 (Grad) or the Vanilia MLRS Systems, it sometimes takes up to 10 Seconds until the next shot is fired.

**Solution you'd like:**
I would love it, if you could/would change the Modul so that it fires the rockets in a consequent order without interuptions (like in Achilles).

**Alternatives you've considered:**
It could be a nice feature, if you'd able to choose (only needed for MLRS Systems though), if you want a pause between launches or a consequent rain.

**Additional context:**
I honestly love scarying the players by raing down 40 Rockets in 10 Seconds (not necessarly to kill them) but it can give a great Athomsphere especially if you are fighting Russians and Guerilla forces.
I use this Modul a **lot** and it is one of the Main points why i still use Achilles -_-.

**Comment by Kexanone** [comment]
Closed as it is a limitation of `doArtilleryFire`.
