### ISSUE TITLE
Trigger debugger

### ISSUE THREAD

**Issue by Flyingtarta** [zen-mod/ZEN#637]
Being able to see and interact with triggers placed in editor on zeus map, allowing to see information about the trigger, and being able to activate it or delete it. 

I made this feature a stand alone mod, but ill be nice to add, i would like to do a pull request but ill need some help since i dont know how to integrate it, but i want to learn. 

Link from mod in workshop
https://steamcommunity.com/sharedfiles/filedetails/?id=2585755302

Link to github project: 
https://github.com/Flyingtarta/clv_trigger_debugger

**Comment by TheRadiumDude** [comment]
Closing this issue as there's no template filled out yet and this kind of addition is likely out-of-scope. Without full trigger support similar to Eden *(which might not even be possible - see 3D area drawing)*, ZEN would likely not benefit from this kind of integration.
