### ISSUE TITLE
No Marker Position Sync

### ISSUE THREAD

**Issue by Leo15745** [zen-mod/ZEN#638]
**Arma 3 Version:** `2.04` stable
**CBA Version:** `3.15.5` stable
**ZEN Version:** `1.12.0` stable

**Mods**
- CBA_A3
- ZEN

**Description:**
When modifying ZEN created markers' positions and/or light sources' positions (and apparently also other attributes) they are not broadcasted to other clients on a dedicated server.

**Expected behavior:**
All changes should be broadcasted properly to clients of a dedicated server.

**Steps to reproduce:**
Edit position/attributes of a marker/light source on a dedicated server.

**Where did the issue occur?**
Repeatedly on a dedicated server at Nitrado

**Additional information:**
While the initial creation of a marker/light source is synchronized, the modification is apparently not synced  with the other clients of a dedicated server.

**RPT log file:**
None availabe. Sorry.

**Screenshots:**
NA

**Appreciation**
Thank you for the great and continous work on ZEN!

**Comment by Leo15745** [comment]
PS: also vehicle randomizations like civ vehicle colors apparently are not synced properly, resulting in different clients seeing different vehicle colors with the same car.

**Comment by mharis001** [comment]
Is ZEN installed on all machines?

**Comment by Leo15745** [comment]
Yes sir!
But with our last game today we were strangely only able to reconstruct the marker issue: changed ZEN marker positions are apparently only broadcasted when another attribute like marker color is changed.
Maybe yesterday's light source desync was a matter of distance, as all testing today was in the direct vicinity of players and proved to work fine - sorry for the false alarm here and thanks for the quick response anyhow!

**Comment by mharis001** [comment]
What do you mean by "ZEN marker positions"? Markers moving is handled by the engine, not ZEN.

**Comment by mharis001** [comment]
From the provided information, I don't think this is a ZEN issue. Closing.
