### ISSUE TITLE
Double clicking the execute code module results in flicker of all units

### ISSUE THREAD

**Issue by CreepPork** [zen-mod/ZEN#64]
https://i.gyazo.com/a6958d91e7f98811d527ef312cd45e23.mp4

**Comment by mharis001** [comment]
Not much can be done about this. The Zeus icons are hidden when a dialog is opened, and this is just a product of closing the module's display right after it is opened when conditions are not correct. I guess its more visible at a lower FPS.

For the execute code module, this is only if the user clicks the module after it is set to execute globally and for JIP. [reference](https://github.com/zen-mod/ZEN/blob/master/addons/modules/functions/fnc_gui_executeCode.sqf#L28)
