### ISSUE TITLE
Custom compositions not saving attached object's height propperly

### ISSUE THREAD

**Issue by ghost** [zen-mod/ZEN#649]
**Arma 3 Version:** `2.06` (stable)
**CBA Version:** `3.15.6.211004` (stable)
**ZEN Version:** `1.12.1` (stable)

**Mods:**
```
- CBA_A3
- ZEN
```

**Description:**
When attaching any objects, statics, vehicles etc. onto another object, static, vehicle etc.
And then saving them as a composition. When you try to spawn the composition again the attached items will not be at the correct height.

**Expected behavior:**
When I attach an object to another object and save them as a composition for later. I expect them to retain their positions when I spawn a new one as a composition.

**Steps to reproduce:**

1 - Grab a vehicle/object (here on named OBJ 1)
2 - Grab another vehicle/object (here on named OBJ 2)
3 - Disable their simulation
4 - Position OBJ 2 somewhere above OBJ 1
5 - Use the "Attach To" module 
6 - Attach OBJ 2 to OBJ 1
7 - Select OBJ 1 and OBJ 2 which are now attached
8 - Save them as a composition in the groups tab
9 - Spawn the composition

**Where did the issue occur?**
- Dedicated & Self-Hosted Multiplayer

**Additional information:**
Provided is an image of the problem.

Left is the original
Right is the spawned composition

**RPT log file:**
Unsure if its needed for this issue. If it is please reply and ill edit the issue

**Screenshots:**
![image](https://user-images.githubusercontent.com/12870917/138591668-fc5bcff2-a9a1-45d6-b296-4fae7aeb3487.png)

**Comment by mharis001** [comment]
Fixed by #663.
