### ISSUE TITLE
ai respawn

### ISSUE THREAD

**Issue by Stalkerbrumik** [zen-mod/ZEN#653]
**Is your feature request related to a problem?**
I would need a module that would allow ai respawn for zeus and not have to spend hours scripting in Eden 

**Solution you'd like:**
-It would be good if ai respawn using Vanilla Spawn Point, Zeus module objective, vehicle, static weapons or near the place
where killed
-how many times a unit or group can respawn
-determine which points will be used for respawn
-respawn vehicles
-altitude for aircraft, helicopters and drone if they have a crew so as not to respawn on the ground 
-keep waypoint after respawn (not necessary but would be useful)
-mobile respawn
-Respawn Delay
-if they will use the Zeus module objective so that only the side defending it can be respawn on them 

**Alternatives you've considered:**
MCC Sandbox 4 may have respawn squad but it is insufficient or with the help of mp respawn so I can set up a playeble unit and scripts but it takes a few hours

**Comment by TheRadiumDude** [comment]
Hey, please fill out the issue template that I've edited to your original message so all the information is available for us to go through easier.

**Comment by Stalkerbrumik** [comment]
Okay done

**Comment by neilzar** [comment]
I personally think this is out of scope for ZEN.

**Comment by mharis001** [comment]
It seems very complex in terms of UX for Zeus at least and is likely only feasible to setup in 3DEN. I agree with @neilzar and I don't see this being worked on.
