### ISSUE TITLE
Custom Zeus attributes displays to hide certain attributes

### ISSUE THREAD

**Issue by KeryMiler** [zen-mod/ZEN#654]
**Is your enhancement related to a problem?**
Current overhauls of Zeus attributes displays will make Eden Editor Module 'MouduleCuratorSetAttributesObject_f'/'MouduleCuratorSetAttributesPlayer_f'/'MouduleCuratorSetAttributesGroup_f' all lose efficacy and the current attributes screen was getting crowded.

**Solution you'd like:**
A module in Eden Editor which similar to original Eden Editor Module like  'MouduleCuratorSetAttributesObject_f' to turn on or off certain attributes (example. the name blank of the unit) for certain Zeus unit during mission editting.

**Alternatives you've considered:**
A game setting like current ZEN faction filter.

**Additional context:**
No at the momment.

**Comment by Kexanone** [comment]
CBA settings make more sense for this

**Comment by KeryMiler** [comment]
> CBA settings make more sense for this.

That's a good idea too.I will accept that.
