### ISSUE TITLE
AI Suppression Enhancement - Reloading, Infinite Ammo, Fire Types

### ISSUE THREAD

**Issue by Quailsnap** [zen-mod/ZEN#660]
**Is your enhancement related to a problem?**
AI Suppression module features bottomless magazines, infinite ammo, and constant cyclic fire, which can be very repetitive if not used extremely sparingly, and on occasion look extremely silly (e.g. infinitely firing ATGMs).

**Solution you'd like:**
Add a dialog option, default disabled, that allows Zeuses to pick whether or not AI have bottomless magazines, and/or infinite ammo, and/or randomize their rate of fire.

**Alternatives you've considered:**
A different, more organic suppression feature that simply spawns a Invisible Target Soldier (and/or Invisible Target Vehicle) at module location, then forces relevant AI knowsAbout to max.

**Additional context:**
Relevant function - https://github.com/zen-mod/ZEN/blob/master/addons/ai/functions/fnc_suppressiveFire.sqf
ACE3 implementation - https://github.com/acemod/ACE3/blob/master/addons/zeus/functions/fnc_moduleSuppressiveFire.sqf
Achilles implementation - https://github.com/ArmaAchilles/Achilles/blob/f123656459cab7766aa40c32d5ee12d29ebadaae/%40AresModAchillesExpansion/addons/functions_f_achilles/functions/features/fn_SuppressiveFire.sqf
Original PR - https://github.com/zen-mod/ZEN/pull/595

**Comment by mharis001** [comment]
Leaving infinite ammo/bottomless magazines functionality out for now - just more reliable with AI to set ammo. With the new fire modes, the effect should be a lot more convincing and have natural pauses. Can revisit if non-infinite ammo functionality is still wanted.
