### ISSUE TITLE
Convoy Parameters Module & Intersections

### ISSUE THREAD

**Issue by Hobogun** [zen-mod/ZEN#670]
**Arma 3 Version:** `2.08.149102` (stable)
**CBA Version:** `3.15.7` (stable)
**ZEN Version:** `1.12.2` (stable)

**Mods:**
```
- CBA_A3
- ZEN
```

**Description:**
When using the Convoy Parameters module for a group of vehicles, the lead vehicle will often begin to somewhat turn down another road (if going straight) or otherwise get stuck (if turning) at most if not every intersection or point that two roads connect, causing the lead vehicle to often come to a stop, with it then stuttering backwards and forewords. Even when the lead AI vehicle potentially gets back onto the intended road it was meant to drive down, the next vehicle in line can then often suffer the same issue. This sometimes also results in vehicles further back in the convoy just stopping and not moving at all, even if the vehicles before it are moving away.

**Expected behavior:**
A convoy of vehicles able to drive through a intersection or other road connection without stopping and or turning onto the wrong road.

**Steps to reproduce:**
Follow these steps to reproduce the issue.

1. _Open Zeus and spawn a selection of vehicles ..._
2. _Connect the command of the vehicles to the lead vehicle ..._
3. _Follow the instructions as per https://zen-mod.github.io/ZEN/#/user_guide/modules_list to place the Convoy Parameters module on the vehicles. ..._
4. _Give the lead vehicle a waypoint and watch at each intersection or road connection what happens. ..._

**Where did the issue occur?**
- Dedicated & Self-Hosted Multiplayer along with Singleplayer.

**Additional information:**
When not using the Convoy Parameters module and doing it the manual way by assigning the vehicles in the convoy to the lead vehicle, bypassing the module and setting the waypoint, the AI does not suffer the same problem at intersections or road connections.

**RPT log file:**
- This issue does not produce an RPT log error.

**Screenshots:**
In the first screenshot (bottom to top), the lead vehicle which was attempting to go straight in the picture instead turned right onto the right road then after turning right tried to turn left, which left it in a constant moving backwards and forewords stuttering state in the second & third screenshots
![20220529204252_1](https://user-images.githubusercontent.com/30333945/170907757-a6d136e1-4b3b-4338-a7ac-03ad714b7d34.jpg)
![20220529203829_1](https://user-images.githubusercontent.com/30333945/170907770-612b7170-86f0-40fb-a739-73e328b8aeda.jpg)
![20220529203824_1](https://user-images.githubusercontent.com/30333945/170907781-df4624ca-3300-4274-b694-6b2b503ce00d.jpg)

**Comment by mharis001** [comment]
The Convoy Parameters module does not do anything special other than use commands to set the convoy separation, speed limit, and force stay on road. I think this is probably just an issue with Arma 3 AI driving. Try with the stay on road option disabled.

**Comment by mharis001** [comment]
Just Arma driving AI - they probably try to "stay on the road" a little too much which causes them to stutter.
