### ISSUE TITLE
Control vehicle action menu from Zeus

### ISSUE THREAD

**Issue by SochorA3** [zen-mod/ZEN#675]
**Is your feature request related to a problem?**
I've grown really tired of having to remote control a unit driving a vehicle to disable/enable something eg. police lights or sirens.

**Solution you'd like:**
Add a module on the RMB dropdown menu which lets you interact with every action available in the action menu of said unit.

**Alternatives you've considered:**
None.

**Additional context:**
None, my suggestion is pretty clear.

**Comment by mharis001** [comment]
This seems tricky to do and honestly don't see its place on the context menu. Closing as won't do.
