### ISSUE TITLE
Formatting error in dialog will re-execute last working module

### ISSUE THREAD

**Issue by IR0NSIGHT** [zen-mod/ZEN#678]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ZEN Version:** `1.x.x` (stable / dev + commit hash)
**Mods:**
- CBA_A3
- ZEN

**Description:**
I made a formatting error in my slider dialogue, where code formats a number:

```
		[
			"SLIDER",
			["Lethal Range","Will accurately destroy all aircraft inside this radius."],
			[-1,5000,-1,{if (_this < 0) exitWith {"disabled"};  _this}],    //<< _this is number, return must be string
			false
		],
```
upon execution some deep error popped up complaining the a number was returned (_this is a number) and not a string.
when i try to use the "broken" module again, it instead reverts to the last module used that wasnt broken => it re-opens the dialogue to a different module.

Just a tiny, edgecase "bug". Ignore if you like

**Comment by mharis001** [comment]
Not a bug. The formatting is expected to always return a string that is used to set the text for the edit box.
