### ISSUE TITLE
Blufor/Opfor Open All/Collapse All buttons are broken as of latest Arma Patch within Zeus

### ISSUE THREAD

**Issue by Raptoid** [zen-mod/ZEN#680]
**Arma 3 Version:** `2.10` (stable)
**CBA Version:** `3.15.7.220517` (stable)
**ZEN Version:** `1.12.2` (stable)

**Mods:**
```
- CBA_A3
- ZEN
```

**Description:**
Attempting to use the open/close all list in Zeus does not work for either Blufor or Opfor factions, however it does work for Indep/Objects/Modules/Civilians.

**Expected behavior:**
They open and close.

**Steps to reproduce:**
Add the steps needed to reproduce the issue.

1. Open Eden
2. Place player unit
3. Place a gamemaster module
4. set to #adminLogged
5. Start and attempt to open or close all blufor/opfor (only those sides) lists. They do not work.

**Where did the issue occur?**
- Dedicated / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer)
(attempted on all of these)

**Additional information:**
I did get one error when in the editor, but I could not reproduce it, and it was when I accidentally started with additional mods. Everything else has been done with only ZEN and CBA enabled.

22:38:59 Error in expression <((SecondaryWeaponsClassName !="") && { ((isClass (configFile >> "CfgWeapons" >>
22:38:59   Error position: < ((isClass (configFile >> "CfgWeapons" >>
22:38:59   Error Missing }

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

https://pastebin.com/mXr3YsBH

**Screenshots:**
N/A

**Comment by mharis001** [comment]
Known issue; BI changed how the value of `RscDisplayCurator_sections` should be interpreted which causes ZEN code to find the wrong tree for BLUFOR and OPFOR sides. Will be fixed in the next update.
