### ISSUE TITLE
Change side unit

### ISSUE THREAD

**Issue by Stalkerbrumik** [zen-mod/ZEN#683]
Is your feature request related to a problem?
when I make zeus, I need to quickly change sides of units and it is slow when I have to do it through modules, so it would be good if this option was in the context menu or at least with the help of keyboard shortcuts

Solution you'd like
add the option to select a side in the context menu or open the side group module

Alternatives you've considered:
using the keyboard shortcut would open side group module

**Comment by TheRadiumDude** [comment]
Sounds a bit too specific IMO. Is the `Sides` panel in the `Group` attributes not enough? You should be able to change the side of multiple units via selecting them all and doing it via the `Group` attributes.

**Comment by mharis001** [comment]
Yes, too specific for inclusion in ZEN (would clutter the context menu). You can always add your own actions using the API.
