### ISSUE TITLE
Feature Request: Hide ACE zeus modules if replacement exist (e.g. optional pbo)

### ISSUE THREAD

**Issue by bux** [zen-mod/ZEN#69]
As per discussion on ACE3 slack:
![image](https://user-images.githubusercontent.com/1235520/60807478-1d410200-a186-11e9-9bc5-c27ded1b09ce.png)

**Comment by mharis001** [comment]
Thoughts on merging the ACE subcategories ("ACE AI", "ACE Utility", ...) into just "ACE". There are still a 9 left under the "ACE AI" category, so possibly after a couple more are replaced?
