### ISSUE TITLE
Error when trying to spawn "Decorations" of mods in Zeus (factions) (vehicles, helicopters, weapons)

### ISSUE THREAD

**Issue by valen13388** [zen-mod/ZEN#701]
when going to the decorations tab (yellow) both in individual units and in groups, they do not appear directly.

I already confirmed that the problem is from the mod "Zeus Enhanced"

the first 3 images are without the mod.
the other 3 are with the mods.
as can be seen for some reason the error is only found in "Ornaments"
#I have confirmed, have everything activated and  both on the client and on the server
mods used:
https://steamcommunity.com/sharedfiles/filedetails/?id=2916567466

images:
no mod
![Screenshot_80](https://user-images.githubusercontent.com/7896990/212505521-5436f702-a2ce-4fa3-b182-3b5c1130076e.png)
![Screenshot_81](https://user-images.githubusercontent.com/7896990/212505538-338d2f5b-3fd9-4dfb-904e-65d510597f84.png)
![Screenshot_82](https://user-images.githubusercontent.com/7896990/212505546-6b019960-e6ea-4606-bbfa-b82313747f10.png)
si mod
![Screenshot_83](https://user-images.githubusercontent.com/7896990/212507046-6583b335-62bb-47a5-b754-156f132d54d6.png)
![Screenshot_84](https://user-images.githubusercontent.com/7896990/212507059-936ff846-df71-4a0f-a11b-b842da05396d.png)
![Screenshot_85](https://user-images.githubusercontent.com/7896990/212507070-5597b87a-c7f4-4300-879e-f17836738dae.png)

**Comment by ampersand38** [comment]
Those are hidden by the setting Declutter Empty Tree, which you can toggle.
