### ISSUE TITLE
Vehicle Loadout Editor for ACE Interaction Menu

### ISSUE THREAD

**Issue by KiritoSan223** [zen-mod/ZEN#705]
**Is your feature request related to a problem?**
I don't think it's related to a problem.

**Solution you'd like:**
I would love an ACE Interaction Menu Point on a vehicle while the vehicle itself is close to an ammunition truck or a similar logistics point, which opens the vehicle loadout menu you have, when double-clicking armed vehicles (screenshot attached).

**Alternatives you've considered:**
The only alternative is the zeus context menu itself, but this variant isn't working for non-zeus players.

**Additional context:**
![image](https://user-images.githubusercontent.com/25136302/216356889-cdc2e231-7abf-417a-9441-708b6f215cfc.png)

**Comment by mharis001** [comment]
This is out of scope for ZEN as a Zeus enhancement mod and likely won't be done.
