### ISSUE TITLE
Error pop up when using zeus

### ISSUE THREAD

**Issue by HufferFish** [zen-mod/ZEN#708]
**Arma 3 Version:** `2.10.149954` (stable)
**CBA Version:** `3.15.8` (stable)
**ZEN Version:** `1.10.0` (stable)

**Mods:**
```
- CBA_A3
- ZEN
```

**Description:**
When loading into mission and when entering a name while saving composition in Zeus interface an error pops up (Shown in attatched screeshots)

**Expected behavior:**
No error pop us and composition can be named and saved

**Steps to reproduce:**
Add the steps needed to reproduce the issue.

1. Load into/create mission with zeus (Error 1 will show)
2. Play mission as zeus
3. Spawn units (any AI)
4. Select units
5. Go to groups
6. Save group composition
7. Set category
8. Set name (Error 2 will show)

**Where did the issue occur?**
- Dedicated server/Singleplayer/Selfhosted server

**Additional information:**
Mods installed using Arma 3sync

A full reinstall of Arma and mods has not resolved the issue

**RPT log file:**
https://pastebin.com/FN3KqwTb

**Screenshots:**
![zenerror1](https://user-images.githubusercontent.com/125408251/219093962-65a5791e-7a8e-4e20-b385-17215ffadb6a.png)
![zenerror2](https://user-images.githubusercontent.com/125408251/219093993-dd4a4c02-9ba8-49d6-86e1-8baa9ebeef46.png)

**Comment by mharis001** [comment]
ZEN 1.12.0 changed custom compositions to be stored as hash maps instead of arrays. In your mod set, you are using an older version of ZEN (1.10.0) after having played with a newer one. The suggestion here would be to update ZEN to the latest version.
