### ISSUE TITLE
"Alert AI" - Radius Module

### ISSUE THREAD

**Issue by Quailsnap** [zen-mod/ZEN#730]
**Is your feature request related to a problem?**
Frequently, with and without AI mods like LAMBs or VCOM, AI will remain in safe mode when hearing gunshots, or when a group that should have "comms" with them is engaged. Patrols marching in safe mode is common, but it's awkward when they remain in safe mode with their weapons lowered after gunshots ring out in the AO. I frequently find myself going through each AI group and setting them to aware / danger.

**Solution you'd like:**
Changing AI behavior to be alerted earlier is out-of-scope (IMO) for ZEN, but a module that "alerts" all nearby AI in a radius, bringing them out of safe mode and into aware, would help reduce busywork for myself and a lot of Zeuses.

**Alternatives you've considered:**
A keybind to remove AI from safe mode would work as well, though isn't really necessary, since "alerting" them is usually done once per AO.

**Additional context:**
This module could be buffed up to include specific conditions to alert AI, like seeing any ordinance go off, or could be configured to alert Zeus when the AI are aware of enemies.

**Comment by Kexanone** [comment]
Feels rather like a unnecessary module. You don't have to edit the groups one by one... You can select all all groups at once, double click on one of the selected groups, edit their behavior and it will be applied to all selected groups.

**Comment by ampersand38** [comment]
Yeah it's 4 actions.
Box, Attributes [~], Combat, OK

**Comment by Quailsnap** [comment]
Fair enough. This issue can be closed.
