### ISSUE TITLE
Only allow manipulating area markers when in marker tab

### ISSUE THREAD

**Issue by Timi007** [zen-mod/ZEN#731]
**Is your enhancement related to a problem?**
Currently if the map is open all area markers can be moved, deleted and edited even those created in 3DEN. This can lead to accidentally moving or deleting these markers when handling units or objects on the map.

**Solution you'd like:**
Only allow moving, deleting and editing area markers when the user is in the marker creation tab. The editing icon for each area marker is only shown when in the marker creation tab. 

**Alternatives you've considered:**
Alternatively, the ability to manipulate area markers could be toggled with a keybind.

**Additional context:**
This is what I mean by marker creation tab:  
![image](https://user-images.githubusercontent.com/9505872/233791634-2b9cc35f-004d-48f5-82ca-60ad0e3c9dcd.png)

**Comment by ampersand38** [comment]
Can't repro. It seems to be already the case that:
- on the zeus map, markers placed by you are only editable while the markers tab is selected
- 3DEN and player markers cannot be edited (i'm not sure how you're able to do that)

Might be another mod enabling editing of all markers?

**Comment by Timi007** [comment]
That's very interesting. I will try to repro it on my side.

Just to be clear you tried with the area markers? The rectangular ones, not the symbols.

**Comment by ampersand38** [comment]
Oh! Area markers, my bad for completely missing that.
