### ISSUE TITLE
Add CBA Setting for Marker Editing Functionality

### ISSUE THREAD

**Issue by Bob-Murphy** [zen-mod/ZEN#735]
**Is your feature request related to a problem?**
Yes.
The ability to `Support editing all area markers` #676 has lead to the issue that when playing missions/mods like Antistasi, Vindicta, Liberation or else the markers within those missions, which in most cases are essential for the mission running, can be moved, edited and deleted as well.
Hence it can easily happen that people playing those missions/mods and using ZEN could by accident change/delete one or multiple and therefore break their game.

**Solution you'd like:**
Implement a CBA setting which either is disabled by default or at least can be disabled by code within the mod/mission itself.
This way the feature in itself stays available (certainly a good feature and no reason to remove it) but gives creators/players the option to disable it for "safety" reasons. It's better to be able to prevent mishaps in the first place.

**Alternatives you've considered:**
Unfortunately I don't have another easy to implement solution which would give the same functionality and keep the feature within ZEN.

**Additional context:**
If you want to replicate the usecase, subscribe to the Antstasi Mod (https://steamcommunity.com/sharedfiles/filedetails/?id=2867537125), launch it in local hosted with CBA and ZEN loaded and observe that you can edit/delete the markers from Antistasi itseld.

Thank you for your mod.

**Comment by mharis001** [comment]
We could add a setting to control which area markers can be edited. There also already exists a way to blacklist markers through code: https://github.com/zen-mod/ZEN/blob/940dbdffe02f052f99760faf107eb68935f8ebc1/addons/area_markers/XEH_preInit.sqf#L24-L26
