### ISSUE TITLE
Keys folder is missing in the mod

### ISSUE THREAD

**Issue by pdergachev2018** [zen-mod/ZEN#738]
**Arma 3 Version:** `x.xx` (stable / rc / dev)
**CBA Version:** `3.x.x` (stable / dev + commit hash)
**ZEN Version:** `1.14.0`

**Mods:**
```
- CBA_A3
- Zeus Enhanced - ACE3 Compatibility
```

**Description:**
Keys folder is missing after mod update.

**Expected behavior:**
Keys folder with author key inside should be there to have ability to use mod on dedicated servers with keys verification.

**Steps to reproduce:**
Add the steps needed to reproduce the issue.

1. Just navigate to mod folder

**Where did the issue occur?**
Steam workshop

**Additional information:**
Provide any additional information that will help us solve this issue.

**RPT log file:**
- Add a link ([gist](https://gist.github.com) or [pastebin](http://pastebin.com)) to the client and/or server RPT file. An instruction to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

**Screenshots:**

**Comment by Radiumio** [comment]
This is intended, as the compatibility mod is signed with the main mod .bisign, included with the main Zeus Enhanced install.
