### ISSUE TITLE
Add the ability to disembark on ropes in the call for reinforcements menu

### ISSUE THREAD

**Issue by VladossX** [zen-mod/ZEN#740]
This is realistic to do? There is already a normal landing and parachute landing, there is a mod that allows you to land on cables individual unit.Can you add this feature to the menu reinforcements?

**Comment by Kexanone** [comment]
Fastroping requires a mod that provides such a feature. ZEN provide compatibility addons for ACE and as of 1.14.0 also for Duda's advanced rappelling, which when loaded add this feature to the reinforcement module.

**Comment by VladossX** [comment]
I'm sorry, but I can't find this feature in the reinforcements menu. I downloaded "Advanced Rappelling" and "Zeus Enhanced - Advanced Rappelling Compatibility" but the reinforcements menu still has 2 choices, land and parachute

**Comment by Kexanone** [comment]
Not sure why you don't see a "Rappel" option. Open a new issue as bug report and describe in detail how to reproduce it.

**Comment by VladossX** [comment]
I'm sorry, I have not updated the mod. everything is, but it works horribly or not working at all. it hangs in one place, not even on the marker that hangs in the air and does nothing (helicopter).
When I create another helicopter with infantry and manually specify what he does on the marker movement he calmly drops the soldiers on the rope.Do you know anything about this?

**Comment by Kexanone** [comment]
Sounds funny, but no clue how to reproduce it. As I said, make a bug report for it so we can try to follow what you did.

**Comment by VladossX** [comment]
Perhaps instead of writing exactly what I did better to record a video? And send it to this site?

**Comment by Kexanone** [comment]
Feel free to attach a video to your bug report, but we need the other details like SP vs MP, mod set and so on as well.

**Comment by VladossX** [comment]
Once again I apologize. Now everything is working as it should, apparently there was some kind of local error
