### ISSUE TITLE
A way to control whole Squads/Teams through remote control

### ISSUE THREAD

**Issue by TairaBadlands** [zen-mod/ZEN#744]
**Is your feature request related to a problem?**
No

**Solution you'd like:**
A Zeus module or a keybind that makes it so when selected and clicked onto a leader of a team, you can freely control the selected unit and it's members. Just like if you spawned in a team in Eden Editor and pressed "play scenario".

**Alternatives you've considered:**
None

**Additional context:**
I remember a while (like a year) ago, there was another mod that was similar to Zeus Enhanced that had a feature similar to that. I don't remember the name but it's most likely not updated anymore and Zeus Enhanced is better overall. So it would be really cool to see that feature added. 

Thank you for taking the time to read this.

**Comment by Kexanone** [comment]
Closed in favor of #54
