### ISSUE TITLE
Zeus Enhanced makes vanilla factions disappear

### ISSUE THREAD

**Issue by Ruskii228** [zen-mod/ZEN#750]
Hello! I am not sure to which category my issue/question goes to, so I am just going to post it as is and will be happy to provide any necessary files for you to check out :)
Zeus Enhanced made my vanilla factions completely disappear. Even when I load my game ONLY with ZEN and CBA, almost none of them load. Only very specific factions from Contact DLC load which just don't make sense because I never played on Livonia map and its Campaign before. Sure I used those units in Zeus a couple of times, but I never touched any sensitive files afterwards. I tried to find the issue on the internet, but I had no luck. And when I disable Zeus Enhanced, all factions come back with no issues afterwards. Strangely, Arma 3 citizens still appear in the game with nothing missing whatsoever. Did I possibly mess something up or just require a small edit of some obscure file? Thank you for your time!
And yes, issue still appears in a freshly made mission with one Zeus player character with "All Addons" and "All Official Addons" enabled.

![2023-10-07_11-55-06](https://github.com/zen-mod/ZEN/assets/147139266/b1b42db8-e743-4fae-8a6f-1fcfdf1e0a26)
![2023-10-07_11-55-45](https://github.com/zen-mod/ZEN/assets/147139266/e6406076-db43-48c7-b608-22046f8b2b97)
![2023-10-07_11-56-19](https://github.com/zen-mod/ZEN/assets/147139266/f2bb1ba1-d41e-4554-8184-1b3d8f7101ba)

**Comment by neilzar** [comment]
Check the Faction filters in the ZEN settings, most likely you have ticked all those factions to be hidden.

**Comment by Ruskii228** [comment]
Very strangely, it says that settings were overwritten by the client and the server settings still had them On. But yeah it worked flawlessly. Thank you man!
