### ISSUE TITLE
Q: Does ZEN work with units players and block vehicle entry

### ISSUE THREAD

**Issue by mwpowellhtx** [zen-mod/ZEN#757]
Not sure whether or even why a ZEN would be working with units, sides, factions (?), or otherwise blocking player vehicle entry?

Here's my scenario.

- Have a `captive _unit` (`true`)
- He is a member in my group
- I load him into a vehicle
- Have verified in Zeus that the unit is indeed indicating `civilian` colors
- And when he is loaded into the vehicle, the vehicle is also indicating `civilian` colors

Following which, action menu options to get into the vehicle at any position vanish. Driver, passeger, whatever, cannot do it any longer from the action menu.

Have tried with and without _ACE_. _ACE Get In_, met with a similar break. Not sure how they implement that, more casual than `moveIn`, it seems. I am met with a non-response, does not get into the vehicle.

Only when I unload the unit from the vehicle do the actions return.

I have verified that the vehicle, positions, are not `locked`, `lockedDriver`, etc. And when I discover that they could be, I unlock the vehicle. Still, no joy.

Oddly enough, I can force the issue using a `moveIn` command, but that seems like overkill.

I wasn't sure if there was some outside possibility that perhaps ZEN factions might be influencing these conditions?

**Comment by mharis001** [comment]
I don't think this is a ZEN issue. We don't do anything with vehicle locking beside providing the vehicle lock attribute.
