### ISSUE TITLE
Disable Group FSM Module

### ISSUE THREAD

**Issue by bluefieldcreator** [zen-mod/ZEN#767]
**Is your feature request related to a problem?**
A lot of units play with FSM mods such as LAMBS or VCOM, but sometimes they need to disable them so the AI follows certain specific behaviors.

**Solution you'd like:**
A checkbox next to the Place vehicles with crew to spawn with FSM enabled or disabled OR a module to disable the FSM ability of the entire group of AI to which a unit belongs

**Alternatives you've considered:**
Check above.

**Additional context:**
None

**Comment by mharis001** [comment]
You can already do this using the "Abilities" attributes sub-menu when double-clicking a unit. There is a checkbox to `disableAI` "FSM".
