### ISSUE TITLE
It's impossible to change sides

### ISSUE THREAD

**Issue by Uspr111** [zen-mod/ZEN#773]
**Arma 3 Version:** `2.16.151618` (stable)  
**CBA Version:** `3.17.1` (stable)  
**ZEN Version:** `1.15.0` (stable)

**Mods:**
```
- CBA_A3
- ZEN
```

**Description:**
When using the player/bot group editing menu in Zeus, it is not possible to change the group's side. Attempts to change the side through the menu result in no changes, although the "Group Side" module works fine.

**Expected behavior:**
When using the side change menu, the group should switch sides.

**Steps to reproduce:**
1. Open Zeus.
2. Select the group editing option on the player leading the group.
3. Open the "Side" menu.
4. Try to change the side and observe that nothing happens.

**Where did the issue occur?**
- Singleplayer, Multiplayer, MP server

**Additional information:**
The issue appeared after updating ZEN from version 1.14.0 to 1.15.0.

**RPT log file:**
- The RPT log file is empty, without errors.

**Video:**

https://github.com/user-attachments/assets/d38c4acd-af28-4982-89ab-d8d660ad4a69

**Comment by Kexanone** [comment]
This has already been resoled in #770 and will be part of the next update.
