### ISSUE TITLE
Units not spawning

### ISSUE THREAD

**Issue by thearmdancer** [zen-mod/ZEN#778]
**Arma 3 Version:** `2.18` (stable / rc / dev)
**CBA Version:** `3.18.0.241008` (stable / dev + commit hash)
**ZEN Version:** `1.15.1` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ZEN
- ace
```

**Description:**
When I activate the Zeus interface, I am not able to spawn units. In the editor interface I am able to do that, but I am not able to do so in the Zeus. I tried to figure out the problem by disabling all mods except for CBA_A3, ZEN, and ace. However, I was still not able to spawn units. I also had the main DLC's plus the Contact DLC activated.

**Expected behavior:**
I'd like to be able to spawn units in the middle of a game.

**Steps to reproduce:**
Add the steps needed to reproduce the issue.

1. _Go to ..._
2. _Click ..._
3. _See ..._

**Where did the issue occur?**
- Editor (Singleplayer) 

**Additional information:**
Provide any additional information that will help us solve this issue.

**RPT log file:**
- There was no error message

**Screenshots:**

**Comment by Radiumio** [comment]
i was unable to reproduce this issue with the same mods + Contact DLC enabled. possibly a key conflict or Zeus setup issue?
