### ISSUE TITLE
ZEN breaks with a large number of mods.

### ISSUE THREAD

**Issue by Blowout0** [zen-mod/ZEN#779]
**Arma 3 Version:** `2.18` (stable)
**CBA Version:** `3.18.1` (stable)
**ZEN Version:** `1.15.1` (stable)

**Mods:**
```
- @Horror_Mod
- [CYTECH] Core Assets And Functions
- [CYTECH] Dynamic Underground Map
- [Expansion Mod] CBRN 2035
- ace
- ACE - D.U.M.P
- ACE 3 Extension (Animations and Actions)
- ACE Interaction Menu Expansion
- ACSTG AI Cannot See Through Grass
- Advanced Vault System: Remastered
- AK630 M2 Duet
- All-in-One Command Menu (Deluxe)
- Alternative Running
- AMZ- Improved WS Sounds V7.8
- AMZ- IWS - CUP COMPAT
- AMZ- IWS - Global Mobilization COMPAT
- -AMZ- IWS - RHS AIO COMPAT
- Anti-Materiel Rifle 25 KKiv Model 2035
- Armor Plates System
- Automatic Zeus Feeder
- Avenger's S.T.A.L.K.E.R. Patches
- Battle Buddy AI
- Burn 'Em Redux
- CBA_A3
- CBRN Defense Unit - Remastered
- CES Resupply
- CLV_ARMORED
- CLV_CORE
- Cold War Rearmed III
- Cold War Rearmed III - Malden Islands
- Crows Electronic Warfare
- Crows Zeus Additions
- CSF - NEW ACE RHS COMPATIBILITY
- CUP Terrains - Core
- CUP Terrains - CWA
- CUP Terrains - Maps
- CUP Units
- CUP Vehicles
- CUP Weapons
- DCO_ToolBox
- DCO_VUnstuck
- Death and Hit reactions
- DISMEMBERMENT+GORE [SP-MP]
- Drongos Active Protection System
- Drongo's Better AI Gunners
- Drongos Spooks and Anomalies
- Fire Support Plus
- Flying Legends
- Ground Map
- Half Life: Our Benefactors
- Half-Life 2 : Echoes of the Resonance Cascade
- Immersion Cigs
- Improved ACE Arsenal Category
- Improved Melee System
- LAGO KU3K Automatic Rifle
- LAGO KU5K MINIGUN
- LAMBS_Danger.fsm
- LAMBS_RPG
- LAMBS_RPG_CUP
- LAMBS_RPG_RHS
- LAMBS_Suppression
- LAMBS_Turrets
- M40 protective mask
- MrSanchez' Headlamps
- Namalsk [R]
- NIArms All In One (V14 Onwards)
- Our Benefactors: Character Expansion
- Peachy's Zeus Compositions
- RHSAFRF
- RHSGREF
- RHSSAF
- RHSTERRACORE
- RHSUSAF
- Root's Anomalies - Zeus Module
- Root's Effects - Zeus Module
- S&S Expansion: Half-Life
- Sci-fi Support Plus
- Secret Weapons Reloaded
- Simplex Support Services [DEV BUILD]
- Snapping for Eden and Zeus
- SPE44 Ju87 Stuka Siren & Skin
- Speshal Core
- Spotted Enemy Markers
- STALKER Markers
- Tracer Fires
- UMB Armavir
- Volcanic Wasteland
- WebKnight's Zombies and Creatures
- WMO - Walkable Moving Objects -ACE compatability
- ZEI - Zeus and Eden Interiors
- Zeus Deck Boss
- Zeus Enhanced
- ZEUS ENHANCEMENT: TARGET POSITION
- Zeus Framerate Monitor
- Zeus Soundtracks

```

**Description:**
The most important symptom of the anomaly is that it is impossible to move the camera above the horizon vertically. The rest: modules from ZEN don't work, hotkeys from ZEN don't work. Units spawn not at the cursor, but in the lower left corner of the map (as if in the zero position of the X;Y axis relative to the map?). Also some module tabs are missing
This anomaly does not occur on all maps and not always. It has not yet been possible to identify why.
Video demonstration of the anomaly - https://youtu.be/EQXf7wzPrMs
Video showing that on the same build, an anomaly may or may not appear on the same mission launch - https://youtu.be/fyCkY2KRq3s

**Expected behavior:**
Zeus should run fine in principle. I tried running with the same list of modifications, but without ZEN, and this anomalous problem did not occur.

**Steps to reproduce:**

1. _Running a build with lots of modifications. So far my minimum count of when an anomaly can occur is 95_
2. _Create a local game with Zeus mode in multiplayer_
3. _Start a scenario and see if an anomaly occurs or not_
4. _If the anomaly did not occur, return to the main menu, and repeat from step 2, but on a different map._

**Where did the issue occur?**
- Self-Hosted Multiplayer

**Additional information:**
I was able to start “catching” this anomaly with 95 modifications. This list, and from which I am basing myself, are those 95 mods.
That's also how the DLC is installed and runs:
- Spearhead 1944
- CSLA Iron Curtain
- Global Mobilization

The likelihood of reproducing an anomalous bug, in my opinion, depends on the number of modifications. Unfortunately, this is the only version built on my modification collection. Last successful launch of the game with ZEN and my mods was in August, and this problem did not occur. Took a break until this week AND decided to get back into Arma. The first thing I did was to check the build work when encountering this problem. I updated the mods where the authors had created new links and the problem continued. I tried to find the conflicting modification(s) that triggered this by reloading the mod. And found none. The discovery that it was reproducible on some maps and not on others was fortuitous. For example, on the same build, there was no problem on Virtual reality and Chernarus, but there was on Altis. Now for some reason it is on Virtual Reality, and I haven't figured out why. I attach a list of my modifications-minimum, on which I was able to see this problem.

mods-preset - https://gist.github.com/Blowout0/3de73c76850a61d3b6f8a45efd7416fd

UPD. I was able to detect this with 66 mods enabled as well. Already on fewer vanilla maps. I don't check maps from mods based on vanilla ones. As I suspected, it works like probability - the fewer mods active, the less likely to catch this. At least I don't know how to disprove it, given that I don't have much power due to illness.
Here's a list of mods: https://gist.github.com/Blowout0/cc2e5a83b0af898b26ede0a0b29a0937

**RPT log file:**
- https://gist.github.com/Blowout0/6ff776b8de837cd83fab2c47cb2f2a56

**Comment by mharis001** [comment]
Some mod in your mod list is breaking Zeus initialization. That's why, for example, the custom compositions panel isn't hidden or the camera's pitch is limited.

You will need to determine what mod is responsible by narrowing down the mod list until you can reproduce it.

**Comment by Blowout0** [comment]
> Some mod in your mod list is breaking Zeus initialization. That's why, for example, the custom compositions panel isn't hidden or the camera's pitch is limited.
> 
> You will need to determine what mod is responsible by narrowing down the mod list until you can reproduce it.

Is it only ONE mod anyway, or perhaps a combination of them? I've already increased the list of active mods one by one, running and checking if there's a problem. But the result is that I'm treading water.

**Comment by Blowout0** [comment]
I think the problem's really solved. Thank you for explaining what was really going on - that's exactly what I was missing.
