### ISSUE TITLE
Feature Request: Custom Objective Icons

### ISSUE THREAD

**Issue by TheRadiumDude** [zen-mod/ZEN#78]
As much as @CreepPork might gut me for this... 😆 

It would be nice to be able to use the task icons that **Eden** has in the **Custom Objective** module in Zeus. It would help the game master better emphasize their tasks and allow players to much more easily understand their task at a glimpse.

![customobjectiveicons](https://user-images.githubusercontent.com/33351673/61221078-fd768480-a717-11e9-83dd-d5d9d9fed19e.jpg)
![20190715154953_1](https://user-images.githubusercontent.com/33351673/61221211-4a5a5b00-a718-11e9-9cbf-33319bd7026b.jpg)

**Comment by CreepPork** [comment]
I won't gut you or anything but it's a bit of a pain to implement as the custom objective module logic is handled by an FSM.
