### ISSUE TITLE
Lambs danger Reinforcement option not working 

### ISSUE THREAD

**Issue by Holgerhollebolle** [zen-mod/ZEN#784]
<!--

**Arma 3 Version:** `Latest Stable` (stable / rc / dev)
**CBA Version:** `Latest Stable` (stable / dev + commit hash)
**ZEN Version:** `Latest Stable` (stable / dev + commit hash)

**Mods:**
```
- CBA_A3
- ZEN
-Lambs Danger

**Description:**
When you right click on a unit and choose Lambs danger enable reinforcement it has no effect. My gues ist you set the lambsvariable on the unit.  

**Expected behavior:**.
The variable needs to be set on the group.

**Comment by mharis001** [comment]
We need more than a title to investigate an issue.
