### ISSUE TITLE
Ambient flyby doesn't work

### ISSUE THREAD

**Issue by UnRealxInferno** [zen-mod/ZEN#92]
**Arma 3 Version:** Stable
**CBA Version:** Stable
**ZEN Version:** Stable

**Mods:**
```
@ace;@ACEX;@ACE_3_Extension;@ACE_Compat_RHSAFRF;@Task_Force_Arrowhead_Radio;@ACE_Compat_RHSUSAF;@ZEN;@Advanced_Sling_Loading;@Advanced_Towing;@ASR_AI3;@BackpackOnChest;@Blastcore_Edited;@Boxloader_ACE_compatability;@BoxLoader_Vehicle_in_Vehicle_loading;@CBA_A3;@Diwako_ACE_Ragdolling;@dzn_Extended_Jamming;@Enhanced_Movement;@FFV_for_Quadbikes;@GRAD_Trenches;@ILBE_Assault_Pack_TFAR;@Immersion_Cigs;@JSRS_RHS_Vehicles_Sound_Patch;@JSRS_SOUNDMOD;@JSRS_SOUNDMOD_RHS_AFRF_Mod_Pack;@JSRS_SOUNDMOD_RHS_GREF_Mod_Pack;@JSRS_SOUNDMOD_RHS_USAF_Mod_Pack;@MGSR;@Multi-play_Uniforms;@NSS_Admin_Console;@Project_OPFOR;@Radio_Animations;@RHSAFRF;@RHSGREF;@RHSSAF;@RHSUSAF;@ShackTac_User_Interface;@Vanilla_smoke;@ZEC_Zeus_and_Eden_Templates;@ACE_Compat_RHSGREF;@suppress;@immerse;@KP_Ranks;@VSM;@adv_medical;@CUP_Terrains;@CUP_Terrains_CWA;@CUP_Terrains_Maps;@ACE_VSM;@gear_functions;@dzn_arty;@pmc_cars;@KATMEDICAL;@CUP_ACE_Terrains;@swu_immersion;@vcom;@rhsextra;@sps;@beketov;@mdf;@soundscape
```

**Description:**
Ambient flyby does not work

**Steps to reproduce:**
Attempt to use ambient flyby

**Where did the issue occur?**
- Dedicated

**Additional information:**
Doesn't work with modded or unmodded files

**RPT log file:**
Unavailable

**Comment by mharis001** [comment]
I followed the steps to reproduce, the modules works for me. Can you provide more details about when you are experiencing a problem?

**Comment by UnRealxInferno** [comment]
I just drop it down, selected helicopters, jets, nothing happens. No confirmation pop-up, no units appear or anything

**Comment by UnRealxInferno** [comment]
Re-installing this onto the dedicated server fixed the issue, not 100% sure what caused the issue though.

**Comment by mharis001** [comment]
Okay, glad you got it fixed. The ambient flyby spawning happens on the server so missing files on the server would explain it not working.
