### ISSUE TITLE
Garage doesn't apply selection to all selected vehicles but only the first one

### ISSUE THREAD

**Issue by CreepPork** [zen-mod/ZEN#97]
https://gyazo.com/a6108267d250d081f34219b5d32b60a6

**Comment by mharis001** [comment]
There are a couple different ways to go about implementing this:

1. Apply any selected change in the UI to all selected vehicles of the type
    - Would require selecting all options in order to get vehicles with identical customization
2. Apply the current vehicle's customization to all selected vehicles of the type when the garage is closed
    - Personally my least favourite, since exiting the garage without changing anything would still copy the current vehicle's customization onto selected vehicles
3. Add an apply to add button which copies the current vehicle's customization onto selected vehicles
    - Could also be a checkbox which applies the changes on exit.
